/**
 * Comprehensive Chat & Messaging Subsystem Coverage Manifest
 * Defines all discovered features, requirements, test metadata, and mapped cases.
 */

export interface TestCaseDefinition {
	id: string;
	featureId: string;
	feature: string;
	priority: "P0" | "P1" | "P2" | "P3";
	layer: "Unit" | "API" | "Rules" | "E2E";
	scenario: string;
	actors: string;
	preconditions: string;
	steps: string;
	expectedResult: string;
	source: string;
}

export interface FeatureDefinition {
	id: string;
	name: string;
	status: "IMPLEMENTED" | "PARTIAL" | "DOCUMENTED_ONLY" | "OUT_OF_SCOPE";
	description: string;
	sourceLocations: string[];
	mappedCases: string[];
	gaps: string;
}

export const FEATURES: FeatureDefinition[] = [
	{
		id: "CHAT-NAV",
		name: "Chat Entry & Navigation",
		status: "IMPLEMENTED",
		description: "Entry points to /messages and /messages/[cid], deep-linking, auth gating, and empty state.",
		sourceLocations: ["src/pages/messages/index.tsx", "src/pages/messages/[cid].tsx", "src/components/Chat/ChatShell.tsx"],
		mappedCases: ["CHAT-NAV-001", "CHAT-NAV-002", "CHAT-NAV-003", "CHAT-NAV-004", "CHAT-NAV-005"],
		gaps: "None",
	},
	{
		id: "CHAT-DISC",
		name: "User Search & Discovery",
		status: "IMPLEMENTED",
		description: "Autocomplete search for starting direct conversations, minimum length filtering, case-insensitivity.",
		sourceLocations: ["src/pages/api/chat/users/search.ts", "src/components/Chat/NewConversationModal.tsx"],
		mappedCases: ["CHAT-DISC-001", "CHAT-DISC-002", "CHAT-DISC-003", "CHAT-DISC-004", "CHAT-DISC-005"],
		gaps: "None",
	},
	{
		id: "CHAT-CONV",
		name: "Conversation Creation & Lifecycle",
		status: "IMPLEMENTED",
		description: "Deterministic DM creation, self-chat prevention, block enforcement, and org channel creation.",
		sourceLocations: ["src/pages/api/chat/conversations/index.ts", "src/types/chat.ts", "firestore.rules"],
		mappedCases: ["CHAT-CONV-001", "CHAT-CONV-002", "CHAT-CONV-003", "CHAT-CONV-004", "CHAT-CONV-005", "CHAT-CONV-006", "CHAT-CONV-007"],
		gaps: "None",
	},
	{
		id: "CHAT-LIST",
		name: "Conversation List & Previews",
		status: "IMPLEMENTED",
		description: "Display of last message preview, sender details, chronological ordering, and unread badges.",
		sourceLocations: ["src/components/Chat/ConversationSidebar.tsx", "src/components/Chat/ConversationRow.tsx", "src/hooks/chat/useConversations.ts"],
		mappedCases: ["CHAT-LIST-001", "CHAT-LIST-002", "CHAT-LIST-003"],
		gaps: "None",
	},
	{
		id: "CHAT-MSG",
		name: "Text Messages & Boundaries",
		status: "IMPLEMENTED",
		description: "Text message validation, multiline preservation, Unicode/diacritics, and length boundary enforcement.",
		sourceLocations: ["src/pages/api/chat/conversations/[cid]/messages/index.ts", "src/components/Chat/MessageBubble.tsx"],
		mappedCases: ["CHAT-MSG-001", "CHAT-MSG-002", "CHAT-MSG-003", "CHAT-MSG-004", "CHAT-MSG-005", "CHAT-MSG-006", "CHAT-MSG-007"],
		gaps: "None",
	},
	{
		id: "CHAT-SEND",
		name: "Send Interaction & Idempotency",
		status: "IMPLEMENTED",
		description: "Keyboard shortcuts, clientMessageId deduplication, and rate limiting.",
		sourceLocations: ["src/components/Chat/MessageComposer.tsx", "src/pages/api/chat/conversations/[cid]/messages/index.ts"],
		mappedCases: ["CHAT-SEND-001", "CHAT-SEND-002", "CHAT-SEND-003"],
		gaps: "None",
	},
	{
		id: "CHAT-REALTIME",
		name: "Realtime Delivery & Attribution",
		status: "IMPLEMENTED",
		description: "Real-time snapshot synchronization between sender and recipient without page reload.",
		sourceLocations: ["src/hooks/chat/useMessages.ts", "src/components/Chat/MessageList.tsx"],
		mappedCases: ["CHAT-REALTIME-001"],
		gaps: "None",
	},
	{
		id: "CHAT-CONC",
		name: "Concurrency & Ordering",
		status: "IMPLEMENTED",
		description: "Handling concurrent messages from multiple participants and maintaining strict order.",
		sourceLocations: ["src/pages/api/chat/conversations/[cid]/messages/index.ts", "src/hooks/chat/useMessages.ts"],
		mappedCases: ["CHAT-CONC-001"],
		gaps: "None",
	},
	{
		id: "CHAT-HIST",
		name: "History & Pagination",
		status: "IMPLEMENTED",
		description: "Cursor-based pagination loading earlier message batches in chronological order.",
		sourceLocations: ["src/pages/api/chat/conversations/[cid]/messages/index.ts", "src/hooks/chat/useMessages.ts"],
		mappedCases: ["CHAT-HIST-001", "CHAT-HIST-002"],
		gaps: "None",
	},
	{
		id: "CHAT-READ",
		name: "Read Receipts & Unread Tracking",
		status: "IMPLEMENTED",
		description: "Read pointers tracking in conversation and userConversationMeta records.",
		sourceLocations: ["src/pages/api/chat/conversations/[cid]/read.ts", "src/hooks/chat/useMessages.ts", "src/hooks/chat/useConversations.ts"],
		mappedCases: ["CHAT-READ-001", "CHAT-READ-002"],
		gaps: "None",
	},
	{
		id: "CHAT-TYPE",
		name: "Typing Indicators",
		status: "IMPLEMENTED",
		description: "Ephemeral typing document with 4-second expiration and client heartbeat.",
		sourceLocations: ["src/pages/api/chat/conversations/[cid]/typing.ts", "src/hooks/chat/useTyping.ts", "src/components/Chat/TypingIndicator.tsx"],
		mappedCases: ["CHAT-TYPE-001", "CHAT-TYPE-002", "CHAT-TYPE-003"],
		gaps: "None",
	},
	{
		id: "CHAT-REACT",
		name: "Message Reactions",
		status: "IMPLEMENTED",
		description: "Atomic emoji reaction toggling per message.",
		sourceLocations: ["src/pages/api/chat/conversations/[cid]/messages/[mid]/reactions.ts", "src/components/Chat/ReactionBar.tsx"],
		mappedCases: ["CHAT-REACT-001", "CHAT-REACT-002"],
		gaps: "None",
	},
	{
		id: "CHAT-PIN",
		name: "Pinned Messages",
		status: "IMPLEMENTED",
		description: "Pinning and unpinning messages with participant/staff role enforcement.",
		sourceLocations: ["src/pages/api/chat/conversations/[cid]/messages/[mid]/pin.ts", "src/components/Chat/MessageActions.tsx"],
		mappedCases: ["CHAT-PIN-001", "CHAT-PIN-002"],
		gaps: "None",
	},
	{
		id: "CHAT-EDIT",
		name: "Message Edits & Soft Deletions",
		status: "IMPLEMENTED",
		description: "Editing own message within 24h window, and soft-deletion by author or staff.",
		sourceLocations: ["src/pages/api/chat/conversations/[cid]/messages/[mid]/index.ts", "src/components/Chat/MessageActions.tsx"],
		mappedCases: ["CHAT-EDIT-001", "CHAT-EDIT-002", "CHAT-EDIT-003", "CHAT-EDIT-004", "CHAT-DEL-001", "CHAT-DEL-002", "CHAT-DEL-003"],
		gaps: "None",
	},
	{
		id: "CHAT-MEDIA",
		name: "Attachments & Voice Notes",
		status: "IMPLEMENTED",
		description: "Base64 media upload with magic-byte verification, size limits, and authorized proxy streaming.",
		sourceLocations: ["src/pages/api/chat/upload.ts", "src/pages/api/chat/attachment.ts", "src/hooks/chat/useAuthorizedChatMedia.ts", "src/components/Chat/VoiceRecorder.tsx"],
		mappedCases: ["CHAT-MEDIA-001", "CHAT-MEDIA-002", "CHAT-MEDIA-003", "CHAT-MEDIA-004", "CHAT-MEDIA-005", "CHAT-MEDIA-006", "CHAT-MEDIA-007", "CHAT-MEDIA-008", "CHAT-MEDIA-009"],
		gaps: "None",
	},
	{
		id: "CHAT-PERM",
		name: "Security, Moderation & Blocking",
		status: "IMPLEMENTED",
		description: "Participant authorization, Firestore rules enforcement, user blocking, and message reporting.",
		sourceLocations: ["firestore.rules", "src/pages/api/chat/users/block.ts", "src/pages/api/chat/messages/[mid]/report.ts", "src/utils/authMiddleware.ts"],
		mappedCases: ["CHAT-PERM-001", "CHAT-PERM-002", "CHAT-PERM-003", "CHAT-PERM-004", "CHAT-PERM-005", "CHAT-PERM-006", "CHAT-PERM-007", "CHAT-PERM-008"],
		gaps: "None",
	},
];

export const TEST_CASES: TestCaseDefinition[] = [
	// CHAT-NAV
	{
		id: "CHAT-NAV-001",
		featureId: "CHAT-NAV",
		feature: "Chat Entry & Navigation",
		priority: "P0",
		layer: "E2E",
		scenario: "Unauthenticated visitor accessing /messages",
		actors: "Unauthenticated Guest",
		preconditions: "No active Firebase session in browser context",
		steps: "1. Navigate to /messages. 2. Observe displayed content.",
		expectedResult: "Displays sign-in prompt modal/button without exposing any conversation data",
		source: "src/pages/messages/index.tsx",
	},
	{
		id: "CHAT-NAV-002",
		featureId: "CHAT-NAV",
		feature: "Chat Entry & Navigation",
		priority: "P0",
		layer: "E2E",
		scenario: "Authenticated user accessing /messages",
		actors: "User A",
		preconditions: "User A is authenticated",
		steps: "1. Navigate to /messages. 2. Wait for conversation list to load.",
		expectedResult: "Renders ChatShell with sidebar, topbar, and conversation list",
		source: "src/pages/messages/index.tsx",
	},
	{
		id: "CHAT-NAV-003",
		featureId: "CHAT-NAV",
		feature: "Chat Entry & Navigation",
		priority: "P1",
		layer: "E2E",
		scenario: "Deep-linking directly to a conversation (/messages/[cid])",
		actors: "User A",
		preconditions: "User A is a participant in conversation CID",
		steps: "1. Navigate directly to /messages/{cid}. 2. Check active conversation.",
		expectedResult: "Active conversation header and message stream load for the specified CID",
		source: "src/pages/messages/[cid].tsx",
	},
	{
		id: "CHAT-NAV-004",
		featureId: "CHAT-NAV",
		feature: "Chat Entry & Navigation",
		priority: "P2",
		layer: "E2E",
		scenario: "Deep-linking to non-existent conversation ID",
		actors: "User A",
		preconditions: "User A is authenticated; conversation ID does not exist",
		steps: "1. Navigate to /messages/non_existent_cid_99999. 2. Observe UI.",
		expectedResult: "Shows clean fallback/empty state without unhandled JavaScript crashes",
		source: "src/components/Chat/ChatShell.tsx",
	},
	{
		id: "CHAT-NAV-005",
		featureId: "CHAT-NAV",
		feature: "Chat Entry & Navigation",
		priority: "P2",
		layer: "E2E",
		scenario: "Desktop auto-selection of first conversation",
		actors: "User A",
		preconditions: "Desktop viewport (width >= 768px); user has at least one conversation",
		steps: "1. Open /messages on desktop. 2. Wait for conversations to load.",
		expectedResult: "First conversation in list is automatically selected in the main panel",
		source: "src/components/Chat/ChatShell.tsx",
	},

	// CHAT-DISC
	{
		id: "CHAT-DISC-001",
		featureId: "CHAT-DISC",
		feature: "User Search & Discovery",
		priority: "P1",
		layer: "API",
		scenario: "Search users by username query",
		actors: "User A",
		preconditions: "Target user with known username exists in users collection",
		steps: "1. Call GET /api/chat/users/search?q={username}.",
		expectedResult: "Returns 200 with matching user in results array",
		source: "src/pages/api/chat/users/search.ts",
	},
	{
		id: "CHAT-DISC-002",
		featureId: "CHAT-DISC",
		feature: "User Search & Discovery",
		priority: "P1",
		layer: "API",
		scenario: "Search users by displayName query",
		actors: "User A",
		preconditions: "Target user with known displayName exists",
		steps: "1. Call GET /api/chat/users/search?q={displayName}.",
		expectedResult: "Returns 200 with matching user record",
		source: "src/pages/api/chat/users/search.ts",
	},
	{
		id: "CHAT-DISC-003",
		featureId: "CHAT-DISC",
		feature: "User Search & Discovery",
		priority: "P2",
		layer: "API",
		scenario: "Search query shorter than 2 characters",
		actors: "User A",
		preconditions: "User A is authenticated",
		steps: "1. Call GET /api/chat/users/search?q=a.",
		expectedResult: "Returns 200 with empty users list (min length guard)",
		source: "src/pages/api/chat/users/search.ts",
	},
	{
		id: "CHAT-DISC-004",
		featureId: "CHAT-DISC",
		feature: "User Search & Discovery",
		priority: "P2",
		layer: "API",
		scenario: "Self-exclusion from search results",
		actors: "User A",
		preconditions: "Query matches User A's own username",
		steps: "1. Call GET /api/chat/users/search with User A's username.",
		expectedResult: "Returns 200 without User A in the results list",
		source: "src/pages/api/chat/users/search.ts",
	},
	{
		id: "CHAT-DISC-005",
		featureId: "CHAT-DISC",
		feature: "User Search & Discovery",
		priority: "P2",
		layer: "API",
		scenario: "Search with special/Unicode characters",
		actors: "User A",
		preconditions: "User A is authenticated",
		steps: "1. Call GET /api/chat/users/search?q=%F0%9F%94%A5%20test.",
		expectedResult: "Returns 200 without error",
		source: "src/pages/api/chat/users/search.ts",
	},

	// CHAT-CONV
	{
		id: "CHAT-CONV-001",
		featureId: "CHAT-CONV",
		feature: "Conversation Creation & Lifecycle",
		priority: "P0",
		layer: "API",
		scenario: "Creating new direct conversation between User A and User B",
		actors: "User A, User B",
		preconditions: "No prior DM exists between User A and User B",
		steps: "1. POST /api/chat/conversations with type='direct' and targetUid=UserB.uid.",
		expectedResult: "Returns 201 with new conversation having canonical ID 'dm_{sortedUids}' and isExisting=false",
		source: "src/pages/api/chat/conversations/index.ts",
	},
	{
		id: "CHAT-CONV-002",
		featureId: "CHAT-CONV",
		feature: "Conversation Creation & Lifecycle",
		priority: "P1",
		layer: "API",
		scenario: "Requesting direct conversation when one already exists",
		actors: "User A, User B",
		preconditions: "Conversation between User A and User B already exists",
		steps: "1. Repeat POST /api/chat/conversations with same targetUid.",
		expectedResult: "Returns 200 with existing conversation and isExisting=true (idempotent)",
		source: "src/pages/api/chat/conversations/index.ts",
	},
	{
		id: "CHAT-CONV-003",
		featureId: "CHAT-CONV",
		feature: "Conversation Creation & Lifecycle",
		priority: "P1",
		layer: "API",
		scenario: "Attempting to create a self-conversation",
		actors: "User A",
		preconditions: "User A is authenticated",
		steps: "1. POST /api/chat/conversations with targetUid=UserA.uid.",
		expectedResult: "Returns 400 Bad Request with error: 'cannot start a direct message with yourself'",
		source: "src/pages/api/chat/conversations/index.ts",
	},
	{
		id: "CHAT-CONV-004",
		featureId: "CHAT-CONV",
		feature: "Conversation Creation & Lifecycle",
		priority: "P1",
		layer: "API",
		scenario: "Attempting to create DM when blocked",
		actors: "User A, User D (blocked)",
		preconditions: "User A has blocked User D (or vice-versa in userBlocks)",
		steps: "1. POST /api/chat/conversations with targetUid=UserD.uid.",
		expectedResult: "Returns 403 Forbidden with error: 'Direct messaging is unavailable between these users'",
		source: "src/pages/api/chat/conversations/index.ts",
	},
	{
		id: "CHAT-CONV-005",
		featureId: "CHAT-CONV",
		feature: "Conversation Creation & Lifecycle",
		priority: "P1",
		layer: "API",
		scenario: "Creating organization channel as org staff/owner",
		actors: "Org Staff",
		preconditions: "Org Staff has 'owner' or 'admin' role in organization",
		steps: "1. POST /api/chat/conversations with type='organization_channel', title, organizationId.",
		expectedResult: "Returns 201 with newly created org channel",
		source: "src/pages/api/chat/conversations/index.ts",
	},
	{
		id: "CHAT-CONV-006",
		featureId: "CHAT-CONV",
		feature: "Conversation Creation & Lifecycle",
		priority: "P1",
		layer: "API",
		scenario: "Creating organization channel as ordinary non-staff member",
		actors: "Regular Member",
		preconditions: "Regular Member has role 'member' in organization",
		steps: "1. POST /api/chat/conversations with type='organization_channel'.",
		expectedResult: "Returns 403 Forbidden: Insufficient permissions to create organization channels",
		source: "src/pages/api/chat/conversations/index.ts",
	},
	{
		id: "CHAT-CONV-007",
		featureId: "CHAT-CONV",
		feature: "Conversation Creation & Lifecycle",
		priority: "P2",
		layer: "API",
		scenario: "Creating duplicate channel with conflicting name in same org",
		actors: "Org Staff",
		preconditions: "Channel with title 'general' already exists in organization",
		steps: "1. POST /api/chat/conversations with same title 'general' in same org.",
		expectedResult: "Returns 409 Conflict: 'A channel with this name already exists'",
		source: "src/pages/api/chat/conversations/index.ts",
	},

	// CHAT-LIST
	{
		id: "CHAT-LIST-001",
		featureId: "CHAT-LIST",
		feature: "Conversation List & Previews",
		priority: "P1",
		layer: "API",
		scenario: "Conversation list includes last message preview and sender details",
		actors: "User A",
		preconditions: "User A has conversation with at least one sent message",
		steps: "1. Call GET /api/chat/conversations.",
		expectedResult: "Conversation object has lastMessagePreview, lastMessageSenderId, and lastActivityAt",
		source: "src/pages/api/chat/conversations/index.ts",
	},
	{
		id: "CHAT-LIST-002",
		featureId: "CHAT-LIST",
		feature: "Conversation List & Previews",
		priority: "P1",
		layer: "API",
		scenario: "Conversations are ordered by lastActivityAt descending",
		actors: "User A",
		preconditions: "User A has multiple conversations with varying activity timestamps",
		steps: "1. Call GET /api/chat/conversations. 2. Verify ordering.",
		expectedResult: "Conversations array is sorted with newest lastActivityAt first",
		source: "src/pages/api/chat/conversations/index.ts",
	},
	{
		id: "CHAT-LIST-003",
		featureId: "CHAT-LIST",
		feature: "Conversation List & Previews",
		priority: "P1",
		layer: "API",
		scenario: "Recipient unread status computation",
		actors: "User A, User B",
		preconditions: "User B sent a message after User A's lastReadAt",
		steps: "1. GET /api/chat/conversations as User A.",
		expectedResult: "Conversation has isUnread === true",
		source: "src/pages/api/chat/conversations/index.ts",
	},

	// CHAT-MSG
	{
		id: "CHAT-MSG-001",
		featureId: "CHAT-MSG",
		feature: "Text Messages & Boundaries",
		priority: "P0",
		layer: "API",
		scenario: "Sending standard text message",
		actors: "User A",
		preconditions: "User A is participant in conversation CID",
		steps: "1. POST /api/chat/conversations/{cid}/messages with text='Hello World'.",
		expectedResult: "Returns 201 with message document having text, senderId, and createdAt",
		source: "src/pages/api/chat/conversations/[cid]/messages/index.ts",
	},
	{
		id: "CHAT-MSG-002",
		featureId: "CHAT-MSG",
		feature: "Text Messages & Boundaries",
		priority: "P1",
		layer: "API",
		scenario: "Sending multiline content with preserved line breaks",
		actors: "User A",
		preconditions: "User A is participant in CID",
		steps: "1. POST /api/chat/conversations/{cid}/messages with text containing newlines ('Line 1\\nLine 2').",
		expectedResult: "Returns 201 and persists newlines intact",
		source: "src/pages/api/chat/conversations/[cid]/messages/index.ts",
	},
	{
		id: "CHAT-MSG-003",
		featureId: "CHAT-MSG",
		feature: "Text Messages & Boundaries",
		priority: "P1",
		layer: "API",
		scenario: "Sending empty or whitespace-only message",
		actors: "User A",
		preconditions: "User A is participant in CID",
		steps: "1. POST /api/chat/conversations/{cid}/messages with text='   '.",
		expectedResult: "Returns 400 Bad Request: 'Message content cannot be empty'",
		source: "src/pages/api/chat/conversations/[cid]/messages/index.ts",
	},
	{
		id: "CHAT-MSG-004",
		featureId: "CHAT-MSG",
		feature: "Text Messages & Boundaries",
		priority: "P1",
		layer: "API",
		scenario: "Sending Unicode, Vietnamese diacritics, and emoji characters",
		actors: "User A",
		preconditions: "User A is participant in CID",
		steps: "1. POST message with text='Xin chào! 🔥 Chúc bạn code tốt! 🚀 👨‍💻'.",
		expectedResult: "Returns 201 and stores all characters, diacritics, and composite emojis accurately",
		source: "src/pages/api/chat/conversations/[cid]/messages/index.ts",
	},
	{
		id: "CHAT-MSG-005",
		featureId: "CHAT-MSG",
		feature: "Text Messages & Boundaries",
		priority: "P2",
		layer: "API",
		scenario: "Sending message at max length boundary (15,000 characters)",
		actors: "User A",
		preconditions: "User A is participant in CID",
		steps: "1. Generate text of exactly 15,000 characters. 2. POST to messages endpoint.",
		expectedResult: "Returns 201 Created and persists message",
		source: "src/pages/api/chat/conversations/[cid]/messages/index.ts",
	},
	{
		id: "CHAT-MSG-006",
		featureId: "CHAT-MSG",
		feature: "Text Messages & Boundaries",
		priority: "P2",
		layer: "API",
		scenario: "Sending message exceeding max length (>15,000 characters)",
		actors: "User A",
		preconditions: "User A is participant in CID",
		steps: "1. Generate text of 15,001 characters. 2. POST to messages endpoint.",
		expectedResult: "Returns 400 Bad Request: 'Message exceeds maximum length of 15,000 characters'",
		source: "src/pages/api/chat/conversations/[cid]/messages/index.ts",
	},
	{
		id: "CHAT-MSG-007",
		featureId: "CHAT-MSG",
		feature: "Text Messages & Boundaries",
		priority: "P2",
		layer: "Unit",
		scenario: "Mention extraction from message text",
		actors: "System",
		preconditions: "Input text contains @valid_username and @invalid",
		steps: "1. Execute mention parsing regex matching pattern /@([a-zA-Z0-9_]{3,20})/g.",
		expectedResult: "Correctly extracts unique valid mention handles",
		source: "src/pages/api/chat/conversations/[cid]/messages/index.ts",
	},

	// CHAT-SEND
	{
		id: "CHAT-SEND-001",
		featureId: "CHAT-SEND",
		feature: "Send Interaction & Idempotency",
		priority: "P1",
		layer: "API",
		scenario: "Message submission with clientMessageId",
		actors: "User A",
		preconditions: "Unique clientMessageId generated",
		steps: "1. POST message with clientMessageId='cm_test_123'.",
		expectedResult: "Returns 201 with clientMessageId stored on document",
		source: "src/pages/api/chat/conversations/[cid]/messages/index.ts",
	},
	{
		id: "CHAT-SEND-002",
		featureId: "CHAT-SEND",
		feature: "Send Interaction & Idempotency",
		priority: "P1",
		layer: "API",
		scenario: "Duplicate resend with identical clientMessageId",
		actors: "User A",
		preconditions: "Message with clientMessageId='cm_test_123' already created",
		steps: "1. Resend POST with same clientMessageId='cm_test_123'.",
		expectedResult: "Returns 200 with existing message and isDuplicate=true without creating duplicate row",
		source: "src/pages/api/chat/conversations/[cid]/messages/index.ts",
	},
	{
		id: "CHAT-SEND-003",
		featureId: "CHAT-SEND",
		feature: "Send Interaction & Idempotency",
		priority: "P2",
		layer: "API",
		scenario: "Exceeding rate limit threshold (>30 msgs/min)",
		actors: "User A",
		preconditions: "User A sends 31 messages rapidly within 60s window",
		steps: "1. Execute burst of message sends. 2. Inspect response on 31st request.",
		expectedResult: "Returns 429 Too Many Requests: 'You are sending messages too quickly'",
		source: "src/pages/api/chat/conversations/[cid]/messages/index.ts",
	},

	// CHAT-REALTIME
	{
		id: "CHAT-REALTIME-001",
		featureId: "CHAT-REALTIME",
		feature: "Realtime Delivery & Attribution",
		priority: "P0",
		layer: "E2E",
		scenario: "Real-time message delivery from User A to User B in separate browser contexts",
		actors: "User A, User B",
		preconditions: "User A and User B open conversation CID simultaneously in separate sessions",
		steps: "1. User A types and sends 'Realtime ping'. 2. Observe User B's page without refreshing.",
		expectedResult: "User B's message stream updates live showing User A's message, sender name, and correct text",
		source: "src/hooks/chat/useMessages.ts",
	},

	// CHAT-CONC
	{
		id: "CHAT-CONC-001",
		featureId: "CHAT-CONC",
		feature: "Concurrency & Ordering",
		priority: "P1",
		layer: "API",
		scenario: "Simultaneous concurrent message sends by both participants",
		actors: "User A, User B",
		preconditions: "Active conversation CID",
		steps: "1. Dispatch concurrent sends from User A and User B via Promise.all. 2. Query messages.",
		expectedResult: "Both messages persist cleanly with accurate individual attribution and monotonic timestamps",
		source: "src/pages/api/chat/conversations/[cid]/messages/index.ts",
	},

	// CHAT-HIST
	{
		id: "CHAT-HIST-001",
		featureId: "CHAT-HIST",
		feature: "History & Pagination",
		priority: "P1",
		layer: "API",
		scenario: "Paginated message fetch respecting limit query",
		actors: "User A",
		preconditions: "Conversation contains 10 messages",
		steps: "1. Call GET /api/chat/conversations/{cid}/messages?limit=5.",
		expectedResult: "Returns 200 with exactly 5 messages and hasMore=true in chronological order",
		source: "src/pages/api/chat/conversations/[cid]/messages/index.ts",
	},
	{
		id: "CHAT-HIST-002",
		featureId: "CHAT-HIST",
		feature: "History & Pagination",
		priority: "P1",
		layer: "API",
		scenario: "Pagination cursor using 'before' timestamp",
		actors: "User A",
		preconditions: "Conversation contains messages with known timestamps",
		steps: "1. Query page 1. 2. Take oldest message timestamp. 3. Query with ?before={timestamp}&limit=5.",
		expectedResult: "Returns earlier messages strictly preceding the cursor timestamp without duplicates",
		source: "src/pages/api/chat/conversations/[cid]/messages/index.ts",
	},

	// CHAT-READ
	{
		id: "CHAT-READ-001",
		featureId: "CHAT-READ",
		feature: "Read Receipts & Unread Tracking",
		priority: "P1",
		layer: "API",
		scenario: "Marking conversation as read updates read pointers",
		actors: "User A",
		preconditions: "Conversation CID exists",
		steps: "1. Call POST /api/chat/conversations/{cid}/read with messageId and readTimestamp.",
		expectedResult: "Returns 200 and updates readPointers.{uid} in conversation doc and userConversationMeta",
		source: "src/pages/api/chat/conversations/[cid]/read.ts",
	},
	{
		id: "CHAT-READ-002",
		featureId: "CHAT-READ",
		feature: "Read Receipts & Unread Tracking",
		priority: "P1",
		layer: "API",
		scenario: "Unread count reconciliation after marking read",
		actors: "User A",
		preconditions: "User A had unread messages in conversation CID",
		steps: "1. Mark conversation read. 2. GET /api/chat/conversations as User A.",
		expectedResult: "Conversation has isUnread === false",
		source: "src/pages/api/chat/conversations/index.ts",
	},

	// CHAT-TYPE
	{
		id: "CHAT-TYPE-001",
		featureId: "CHAT-TYPE",
		feature: "Typing Indicators",
		priority: "P2",
		layer: "API",
		scenario: "Sending typing heartbeat creates ephemeral record",
		actors: "User A",
		preconditions: "Active conversation CID",
		steps: "1. POST /api/chat/conversations/{cid}/typing.",
		expectedResult: "Returns 200 and creates document in conversations/{cid}/typing/{uid} with expiresAt ~ now+4000",
		source: "src/pages/api/chat/conversations/[cid]/typing.ts",
	},
	{
		id: "CHAT-TYPE-002",
		featureId: "CHAT-TYPE",
		feature: "Typing Indicators",
		priority: "P2",
		layer: "API",
		scenario: "Clearing typing state deletes ephemeral record",
		actors: "User A",
		preconditions: "Typing record exists for User A",
		steps: "1. DELETE /api/chat/conversations/{cid}/typing.",
		expectedResult: "Returns 200 and typing document is removed from subcollection",
		source: "src/pages/api/chat/conversations/[cid]/typing.ts",
	},
	{
		id: "CHAT-TYPE-003",
		featureId: "CHAT-TYPE",
		feature: "Typing Indicators",
		priority: "P2",
		layer: "Unit",
		scenario: "Client typing hook filters out user's own typing",
		actors: "System",
		preconditions: "Typing subcollection snapshot contains user's own UID and partner UID",
		steps: "1. Feed mock snapshot to typing reducer logic.",
		expectedResult: "Only partner's typing state is included; own typing is filtered out",
		source: "src/hooks/chat/useTyping.ts",
	},

	// CHAT-REACT
	{
		id: "CHAT-REACT-001",
		featureId: "CHAT-REACT",
		feature: "Message Reactions",
		priority: "P1",
		layer: "API",
		scenario: "Adding reaction to message",
		actors: "User A",
		preconditions: "Message MID exists in conversation CID",
		steps: "1. POST /api/chat/conversations/{cid}/messages/{mid}/reactions with emoji='🔥'.",
		expectedResult: "Returns 200 and reactions object contains '🔥': [UserA.uid]",
		source: "src/pages/api/chat/conversations/[cid]/messages/[mid]/reactions.ts",
	},
	{
		id: "CHAT-REACT-002",
		featureId: "CHAT-REACT",
		feature: "Message Reactions",
		priority: "P1",
		layer: "API",
		scenario: "Toggling reaction off removes UID and cleans empty key",
		actors: "User A",
		preconditions: "User A has already reacted with '🔥'",
		steps: "1. POST /api/chat/conversations/{cid}/messages/{mid}/reactions with same emoji='🔥'.",
		expectedResult: "Returns 200 and emoji key '🔥' is deleted from reactions object",
		source: "src/pages/api/chat/conversations/[cid]/messages/[mid]/reactions.ts",
	},

	// CHAT-PIN
	{
		id: "CHAT-PIN-001",
		featureId: "CHAT-PIN",
		feature: "Pinned Messages",
		priority: "P1",
		layer: "API",
		scenario: "Direct message participant pins message",
		actors: "User A",
		preconditions: "Direct message conversation CID contains message MID",
		steps: "1. POST /api/chat/conversations/{cid}/messages/{mid}/pin.",
		expectedResult: "Returns 200 with isPinned=true, pinnedAt timestamp, pinnedBy=UserA.uid",
		source: "src/pages/api/chat/conversations/[cid]/messages/[mid]/pin.ts",
	},
	{
		id: "CHAT-PIN-002",
		featureId: "CHAT-PIN",
		feature: "Pinned Messages",
		priority: "P2",
		layer: "API",
		scenario: "Non-staff user attempts to pin in organization channel",
		actors: "Regular Member",
		preconditions: "Regular Member belongs to org but lacks staff role",
		steps: "1. POST /api/chat/conversations/{orgCid}/messages/{mid}/pin.",
		expectedResult: "Returns 403 Forbidden: 'You do not have permission to pin messages in this channel'",
		source: "src/pages/api/chat/conversations/[cid]/messages/[mid]/pin.ts",
	},

	// CHAT-EDIT
	{
		id: "CHAT-EDIT-001",
		featureId: "CHAT-EDIT",
		feature: "Message Edits & Soft Deletions",
		priority: "P1",
		layer: "API",
		scenario: "Author edits message within 24 hours",
		actors: "User A",
		preconditions: "User A sent message MID within last 24h",
		steps: "1. PATCH /api/chat/conversations/{cid}/messages/{mid} with new text.",
		expectedResult: "Returns 200 with isEdited=true, editedAt timestamp, and updated text",
		source: "src/pages/api/chat/conversations/[cid]/messages/[mid]/index.ts",
	},
	{
		id: "CHAT-EDIT-002",
		featureId: "CHAT-EDIT",
		feature: "Message Edits & Soft Deletions",
		priority: "P1",
		layer: "API",
		scenario: "Non-author attempts to edit another user's message",
		actors: "User B",
		preconditions: "Message MID was sent by User A",
		steps: "1. PATCH /api/chat/conversations/{cid}/messages/{mid} as User B.",
		expectedResult: "Returns 403 Forbidden: 'You can only edit your own messages'",
		source: "src/pages/api/chat/conversations/[cid]/messages/[mid]/index.ts",
	},
	{
		id: "CHAT-EDIT-003",
		featureId: "CHAT-EDIT",
		feature: "Message Edits & Soft Deletions",
		priority: "P2",
		layer: "API",
		scenario: "Author attempts to edit message older than 24 hours",
		actors: "User A",
		preconditions: "Message MID createdAt is older than 24 hours",
		steps: "1. PATCH /api/chat/conversations/{cid}/messages/{mid}.",
		expectedResult: "Returns 400 Bad Request: 'Messages can only be edited within 24 hours'",
		source: "src/pages/api/chat/conversations/[cid]/messages/[mid]/index.ts",
	},
	{
		id: "CHAT-EDIT-004",
		featureId: "CHAT-EDIT",
		feature: "Message Edits & Soft Deletions",
		priority: "P2",
		layer: "API",
		scenario: "Attempting to edit an already-deleted message",
		actors: "User A",
		preconditions: "Message MID has isDeleted === true",
		steps: "1. PATCH /api/chat/conversations/{cid}/messages/{mid}.",
		expectedResult: "Returns 400 Bad Request: 'Cannot edit a deleted message'",
		source: "src/pages/api/chat/conversations/[cid]/messages/[mid]/index.ts",
	},

	// CHAT-DEL
	{
		id: "CHAT-DEL-001",
		featureId: "CHAT-EDIT",
		feature: "Message Edits & Soft Deletions",
		priority: "P1",
		layer: "API",
		scenario: "Author soft-deletes their own message",
		actors: "User A",
		preconditions: "User A sent message MID",
		steps: "1. DELETE /api/chat/conversations/{cid}/messages/{mid}.",
		expectedResult: "Returns 200 with isDeleted=true, text='This message was deleted', attachments cleared",
		source: "src/pages/api/chat/conversations/[cid]/messages/[mid]/index.ts",
	},
	{
		id: "CHAT-DEL-002",
		featureId: "CHAT-EDIT",
		feature: "Message Edits & Soft Deletions",
		priority: "P1",
		layer: "API",
		scenario: "Non-author regular user attempts to delete another's message",
		actors: "User B",
		preconditions: "Message MID was sent by User A; User B is not staff or admin",
		steps: "1. DELETE /api/chat/conversations/{cid}/messages/{mid} as User B.",
		expectedResult: "Returns 403 Forbidden: 'You do not have permission to delete this message'",
		source: "src/pages/api/chat/conversations/[cid]/messages/[mid]/index.ts",
	},
	{
		id: "CHAT-DEL-003",
		featureId: "CHAT-EDIT",
		feature: "Message Edits & Soft Deletions",
		priority: "P2",
		layer: "API",
		scenario: "Org staff deletes inappropriate message in channel",
		actors: "Org Staff",
		preconditions: "Org Staff is admin/moderator in org channel; message was sent by member",
		steps: "1. DELETE /api/chat/conversations/{orgCid}/messages/{mid} as Org Staff.",
		expectedResult: "Returns 200 and soft-deletes message with deletedBy=OrgStaff.uid",
		source: "src/pages/api/chat/conversations/[cid]/messages/[mid]/index.ts",
	},

	// CHAT-MEDIA
	{
		id: "CHAT-MEDIA-001",
		featureId: "CHAT-MEDIA",
		feature: "Attachments & Voice Notes",
		priority: "P1",
		layer: "API",
		scenario: "Upload valid PNG image attachment",
		actors: "User A",
		preconditions: "User A is participant in CID; valid base64 PNG data with magic bytes",
		steps: "1. POST /api/chat/upload with fileData, fileName='photo.png', conversationId=CID.",
		expectedResult: "Returns 201 with category='images', mimeType='image/png', permanent proxy URL",
		source: "src/pages/api/chat/upload.ts",
	},
	{
		id: "CHAT-MEDIA-002",
		featureId: "CHAT-MEDIA",
		feature: "Attachments & Voice Notes",
		priority: "P1",
		layer: "API",
		scenario: "Upload valid PDF document attachment",
		actors: "User A",
		preconditions: "User A is participant in CID; valid base64 PDF header %PDF-",
		steps: "1. POST /api/chat/upload with fileData, fileName='notes.pdf'.",
		expectedResult: "Returns 201 with category='documents', mimeType='application/pdf'",
		source: "src/pages/api/chat/upload.ts",
	},
	{
		id: "CHAT-MEDIA-003",
		featureId: "CHAT-MEDIA",
		feature: "Attachments & Voice Notes",
		priority: "P1",
		layer: "API",
		scenario: "Upload valid audio note with duration",
		actors: "User A",
		preconditions: "User A is participant in CID; valid base64 WebM audio header",
		steps: "1. POST /api/chat/upload with audio fileData and duration=12.",
		expectedResult: "Returns 201 with category='audio', duration=12, mimeType='audio/webm'",
		source: "src/pages/api/chat/upload.ts",
	},
	{
		id: "CHAT-MEDIA-004",
		featureId: "CHAT-MEDIA",
		feature: "Attachments & Voice Notes",
		priority: "P2",
		layer: "API",
		scenario: "Upload empty (0-byte) file",
		actors: "User A",
		preconditions: "User A is participant in CID; base64 payload has 0 bytes",
		steps: "1. POST /api/chat/upload with empty base64 string.",
		expectedResult: "Returns 400 Bad Request: 'File is empty (0 bytes)'",
		source: "src/pages/api/chat/upload.ts",
	},
	{
		id: "CHAT-MEDIA-005",
		featureId: "CHAT-MEDIA",
		feature: "Attachments & Voice Notes",
		priority: "P2",
		layer: "API",
		scenario: "Upload file exceeding 15MB limit",
		actors: "User A",
		preconditions: "File size is 16MB",
		steps: "1. POST /api/chat/upload with >15MB base64 data.",
		expectedResult: "Returns 400 Bad Request: 'File exceeds 15MB limit'",
		source: "src/pages/api/chat/upload.ts",
	},
	{
		id: "CHAT-MEDIA-006",
		featureId: "CHAT-MEDIA",
		feature: "Attachments & Voice Notes",
		priority: "P2",
		layer: "API",
		scenario: "Upload file with spoofed extension and invalid magic bytes",
		actors: "User A",
		preconditions: "Binary data has non-image header but named 'virus.png'",
		steps: "1. POST /api/chat/upload with invalid binary payload.",
		expectedResult: "Returns 400 Bad Request: 'Unsupported file type'",
		source: "src/pages/api/chat/upload.ts",
	},
	{
		id: "CHAT-MEDIA-007",
		featureId: "CHAT-MEDIA",
		feature: "Attachments & Voice Notes",
		priority: "P1",
		layer: "API",
		scenario: "Authorized conversation participant streams attachment via proxy",
		actors: "User A",
		preconditions: "Attachment uploaded to conversation CID",
		steps: "1. GET /api/chat/attachment?cid={cid}&path={fileName} with User A's token.",
		expectedResult: "Returns 200 with accurate Content-Type and binary file stream",
		source: "src/pages/api/chat/attachment.ts",
	},
	{
		id: "CHAT-MEDIA-008",
		featureId: "CHAT-MEDIA",
		feature: "Attachments & Voice Notes",
		priority: "P0",
		layer: "API",
		scenario: "Outsider User C attempts to download private attachment",
		actors: "User C (outsider)",
		preconditions: "Attachment belongs to CID where User C is NOT a participant",
		steps: "1. GET /api/chat/attachment?cid={cid}&path={fileName} with User C's token.",
		expectedResult: "Returns 403 Forbidden: 'Access denied to attachment' (IDOR protection)",
		source: "src/pages/api/chat/attachment.ts",
	},
	{
		id: "CHAT-MEDIA-009",
		featureId: "CHAT-MEDIA",
		feature: "Attachments & Voice Notes",
		priority: "P1",
		layer: "API",
		scenario: "Path traversal attempt in attachment query (?path=../../etc/passwd)",
		actors: "User A",
		preconditions: "User A is authenticated",
		steps: "1. GET /api/chat/attachment?cid={cid}&path=../../package.json.",
		expectedResult: "Returns 403 Forbidden: 'Invalid file path'",
		source: "src/pages/api/chat/attachment.ts",
	},

	// CHAT-PERM
	{
		id: "CHAT-PERM-001",
		featureId: "CHAT-PERM",
		feature: "Security, Moderation & Blocking",
		priority: "P0",
		layer: "Rules",
		scenario: "Firestore rules deny outsider User C reading /conversations/{cid}",
		actors: "User C (outsider)",
		preconditions: "User C is not in CID's participantUids",
		steps: "1. Authenticate client SDK as User C. 2. Attempt getDoc(doc(firestore, 'conversations', cid)).",
		expectedResult: "Firestore rules deny read (permission-denied)",
		source: "firestore.rules",
	},
	{
		id: "CHAT-PERM-002",
		featureId: "CHAT-PERM",
		feature: "Security, Moderation & Blocking",
		priority: "P0",
		layer: "Rules",
		scenario: "Firestore rules deny outsider User C reading /conversations/{cid}/messages",
		actors: "User C (outsider)",
		preconditions: "User C is not in CID's participantUids",
		steps: "1. Authenticate client SDK as User C. 2. Attempt getDocs(collection(firestore, 'conversations', cid, 'messages')).",
		expectedResult: "Firestore rules deny read (permission-denied)",
		source: "firestore.rules",
	},
	{
		id: "CHAT-PERM-003",
		featureId: "CHAT-PERM",
		feature: "Security, Moderation & Blocking",
		priority: "P0",
		layer: "Rules",
		scenario: "Firestore rules deny outsider User C creating messages in someone else's conversation",
		actors: "User C (outsider)",
		preconditions: "User C is not in CID's participantUids",
		steps: "1. Authenticate client SDK as User C. 2. Attempt addDoc in /conversations/{cid}/messages.",
		expectedResult: "Firestore rules deny write (permission-denied)",
		source: "firestore.rules",
	},
	{
		id: "CHAT-PERM-004",
		featureId: "CHAT-PERM",
		feature: "Security, Moderation & Blocking",
		priority: "P0",
		layer: "Rules",
		scenario: "Firestore rules reject spoofed senderId in messages",
		actors: "User A",
		preconditions: "User A is authenticated; attempts to send with senderId=UserB.uid",
		steps: "1. Attempt addDoc with senderId='spoofed_uid'.",
		expectedResult: "Firestore rules reject write because request.resource.data.senderId != request.auth.uid",
		source: "firestore.rules",
	},
	{
		id: "CHAT-PERM-005",
		featureId: "CHAT-PERM",
		feature: "Security, Moderation & Blocking",
		priority: "P1",
		layer: "API",
		scenario: "Direct message send blocked between blocked users",
		actors: "User A, User D (blocked)",
		preconditions: "User A blocked User D",
		steps: "1. POST /api/chat/conversations/{cid}/messages as User D to User A's DM.",
		expectedResult: "Returns 403 Forbidden: 'Cannot send message: this conversation is blocked'",
		source: "src/pages/api/chat/conversations/[cid]/messages/index.ts",
	},
	{
		id: "CHAT-PERM-006",
		featureId: "CHAT-PERM",
		feature: "Security, Moderation & Blocking",
		priority: "P0",
		layer: "API",
		scenario: "Suspended or banned user cannot access chat endpoints",
		actors: "Suspended User",
		preconditions: "User has status='BANNED' in userModeration collection",
		steps: "1. Attempt POST /api/chat/conversations/{cid}/messages with suspended user's token.",
		expectedResult: "Returns 403 Forbidden (blocked by withAuthAndModeration middleware)",
		source: "src/utils/authMiddleware.ts",
	},
	{
		id: "CHAT-PERM-007",
		featureId: "CHAT-PERM",
		feature: "Security, Moderation & Blocking",
		priority: "P2",
		layer: "API",
		scenario: "Message reporting records snapshot in userReports collection",
		actors: "User A",
		preconditions: "Message MID exists in CID",
		steps: "1. POST /api/chat/messages/{mid}/report with conversationId, reason='Harassment'.",
		expectedResult: "Returns 201 with reportId and creates document in userReports with message snapshot",
		source: "src/pages/api/chat/messages/[mid]/report.ts",
	},
	{
		id: "CHAT-PERM-008",
		featureId: "CHAT-PERM",
		feature: "Security, Moderation & Blocking",
		priority: "P0",
		layer: "API",
		scenario: "Unauthenticated client receives 401 across all chat API routes",
		actors: "Unauthenticated Guest",
		preconditions: "No Authorization header",
		steps: "1. Send request without Authorization header to /api/chat/conversations.",
		expectedResult: "Returns 401 Unauthorized: 'Authentication required'",
		source: "src/utils/authMiddleware.ts",
	},
];

export { FEATURES as CHAT_FEATURES, TEST_CASES as CHAT_TEST_CASES, type TestCaseDefinition as TestCaseManifest };
