import { ProblemHyperparameterSpec } from "../hyperparameter-renderer";

export const linearRegressionSpecs: Record<string, ProblemHyperparameterSpec> = {
	"lr-simple-ols-slope-intercept": {
		solverMethod: "Analytical Ordinary Least Squares (OLS) closed form",
		formula: "beta_1 = sum((x_i - x_bar)(y_i - y_bar)) / sum((x_i - x_bar)^2), beta_0 = y_bar - beta_1 * x_bar",
		conventions: "Unbiased closed-form slope and intercept for 2D bivariate data",
		outputPrecision: "Exactly 4 decimal places (beta_0 beta_1)",
		extraConstraints: ["Use exact OLS closed form formulas", "Output: beta_0 beta_1 formatted to 4 decimal places"],
	},
	"lr-regression-through-origin": {
		solverMethod: "Ordinary Least Squares forced through origin (zero intercept, b = 0)",
		formula: "beta = sum(x_i * y_i) / sum(x_i^2)",
		conventions: "Zero intercept model: y = beta * x",
		outputPrecision: "Exactly 4 decimal places (beta)",
		extraConstraints: ["Zero intercept: b = 0", "beta = sum(x*y) / sum(x^2)"],
	},
	"lr-centered-ols-coefficients": {
		solverMethod: "Centered Multiple Linear Regression (mean-subtracted data)",
		formula: "X_c = X - mean(X), y_c = y - mean(y), theta = (X_c^T X_c)^(-1) X_c^T y_c",
		conventions: "Zero intercept on centered coordinates",
		outputPrecision: "Exactly 4 decimal places for each coefficient",
		extraConstraints: ["Center all features and targets before solving", "No intercept term"],
	},
	"lr-standardized-coefficients": {
		solverMethod: "Z-score Standardized Linear Regression (Population Standard Deviation)",
		formula: "z_x = (x - mean(x)) / std_pop(x), z_y = (y - mean(y)) / std_pop(y), beta* = (Z^T Z)^(-1) Z^T z_y",
		conventions: "Use population standard deviation: divide by N (not N-1)",
		outputPrecision: "Exactly 4 decimal places for each standardized coefficient",
		extraConstraints: ["Population std dev: divide by N", "Standardized without intercept"],
	},
	"lr-two-feature-ols-closed-form": {
		solverMethod: "Two-Feature Multiple OLS Regression via Analytical Cramer's Rule / 2x2 Matrix Inverse",
		formula: "theta = (X^T X)^(-1) X^T y where X = [1, x1, x2]",
		conventions: "Intercept theta_0 corresponds to prepended column of 1s",
		outputPrecision: "Exactly 4 decimal places: theta_0 theta_1 theta_2",
		extraConstraints: ["Analytical 2x2 normal equations", "theta_0 is intercept"],
	},
	"lr-multi-target-linear-regression": {
		solverMethod: "Multi-Target Ordinary Least Squares Normal Equation",
		formula: "Theta = (X^T X)^(-1) X^T Y where Y is N x M matrix",
		conventions: "Prepend column of 1s to X for intercept row",
		outputPrecision: "M lines, each with D+1 parameters formatted to 4 decimal places",
		extraConstraints: ["X has intercept column of 1s prepended", "M separate target columns"],
	},
	"lr-polynomial-degree2-expansion": {
		solverMethod: "Quadratic Basis Expansion Linear Curve Fitting",
		formula: "Solve 3x3 normal equations for y = a*x^2 + b*x + c",
		conventions: "Feature matrix columns correspond to [x^2, x, 1] or equivalent basis",
		outputPrecision: "Exactly 4 decimal places: a b c",
		extraConstraints: ["y = a*x^2 + b*x + c", "Output order: a b c formatted to 4 decimals"],
	},
	"lr-categorical-dummy-variable": {
		solverMethod: "Multiple Linear Regression with Binary Categorical Indicator (Dummy Variable)",
		formula: "y = beta_0 + beta_cont * x_cont + beta_cat * x_cat, where x_cat in {0, 1}",
		conventions: "Baseline category is 0, indicator is 1",
		outputPrecision: "Exactly 4 decimal places: beta_0 beta_cont beta_cat",
		extraConstraints: ["x_cat is binary {0, 1}", "Output: beta_0 beta_cont beta_cat"],
	},
	"lr-weighted-bivariate-regression": {
		solverMethod: "Weighted Least Squares (WLS) Simple Linear Regression",
		formula: "x_w = sum(w*x)/sum(w), y_w = sum(w*y)/sum(w), beta_1 = sum(w*(x-x_w)*(y-y_w)) / sum(w*(x-x_w)^2), beta_0 = y_w - beta_1*x_w",
		conventions: "Weights w_i are positive real numbers",
		outputPrecision: "Exactly 4 decimal places: beta_0 beta_1",
		extraConstraints: ["Weighted OLS analytical formulas", "Output: beta_0 beta_1"],
	},
	"lr-orthogonal-distance-regression": {
		solverMethod: "Deming Orthogonal Distance Regression (Perpendicular Residuals)",
		formula: "Minimizes sum of perpendicular squared distances to the line y = beta_0 + beta_1 * x",
		conventions: "Equal error variances in x and y (lambda = 1)",
		outputPrecision: "Exactly 4 decimal places: beta_0 beta_1",
		extraConstraints: ["Deming regression with lambda = 1", "Output: beta_0 beta_1"],
	},
	"lr-constrained-sum-to-one-regression": {
		solverMethod: "Constrained Least Squares Regression via Lagrange Multipliers",
		formula: "min ||Xw - y||^2 subject to sum(w_j) = 1",
		conventions: "Weights sum exactly to 1.0",
		outputPrecision: "D weights space-separated, 4 decimal places",
		extraConstraints: ["Constraint: sum(w_j) == 1", "Solved via KKT / Lagrange multipliers"],
	},
	"lr-linear-spline-fixed-knot": {
		solverMethod: "Piecewise Linear Spline Regression with Fixed Knot c",
		formula: "Basis: [1, x, max(0, x - c)], model: y = beta_0 + beta_1*x + beta_2*max(0, x - c)",
		conventions: "Truncated power basis with knot at position c",
		outputPrecision: "Exactly 4 decimal places: beta_0 beta_1 beta_2",
		extraConstraints: ["Basis: [1, x, max(0, x - c)]", "Output: beta_0 beta_1 beta_2"],
	},
	"lr-interaction-terms-regression": {
		solverMethod: "Two-Feature Multiple Regression with Multiplicative Interaction",
		formula: "Basis: [1, x_1, x_2, x_1 * x_2], model: y = beta_0 + beta_1*x_1 + beta_2*x_2 + beta_inter*(x_1*x_2)",
		conventions: "Interaction term is the elementwise product x_1 * x_2",
		outputPrecision: "Exactly 4 decimal places: beta_0 beta_1 beta_2 beta_inter",
		extraConstraints: ["Include interaction term x1 * x2", "Output: beta_0 beta_1 beta_2 beta_inter"],
	},
	"lr-log-linear-exponential-growth": {
		solverMethod: "Log-Linear Exponential Growth Model Transformation",
		formula: "z = ln(y), fit z = beta_0 + beta_1 * x via OLS, recover a = exp(beta_0), b = beta_1 for y = a * exp(b*x)",
		conventions: "Natural logarithm ln for target transformation",
		outputPrecision: "Exactly 4 decimal places: a b",
		extraConstraints: ["Fit ln(y) = ln(a) + b*x", "Recover a = exp(beta_0), b = beta_1"],
	},
	"lr-power-law-log-log-regression": {
		solverMethod: "Log-Log Power-Law Regression Transformation",
		formula: "u = ln(x), v = ln(y), fit v = beta_0 + beta_1 * u, recover a = exp(beta_0), b = beta_1 for y = a * x^b",
		conventions: "Natural logarithm on both feature and target",
		outputPrecision: "Exactly 4 decimal places: a b",
		extraConstraints: ["Fit ln(y) = ln(a) + b*ln(x)", "Recover a = exp(beta_0), b = beta_1"],
	},
	"lr-normal-equation-direct": {
		solverMethod: "Ordinary Least Squares Normal Equation Matrix Solution",
		formula: "theta = (X^T X)^(-1) X^T y",
		conventions: "Prepend column of 1s to X for intercept term theta_0",
		outputPrecision: "D+1 parameters formatted to 4 decimal places: theta_0 theta_1 ... theta_D",
		extraConstraints: ["Exact closed form: theta = (X^T X)^(-1) X^T y", "Prepend column of 1s for intercept"],
	},
	"lr-normal-equation-determinant": {
		solverMethod: "Gram Matrix Determinant Computation",
		formula: "det(G) where G = X^T X",
		conventions: "Standard matrix determinant of square matrix X^T X",
		outputPrecision: "Real number formatted to 4 decimal places",
		extraConstraints: ["Compute det(X^T X)", "Gram matrix is D x D"],
	},
	"lr-moore-penrose-pseudoinverse": {
		solverMethod: "Moore-Penrose Pseudoinverse Regression via SVD",
		formula: "theta = X^+ y = V * Sigma^+ * U^T * y",
		conventions: "Threshold singular values < 1e-10 to 0",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["SVD pseudoinverse: X^+ = V Sigma^+ U^T", "Singular value cutoff: 1e-10"],
	},
	"lr-ridge-normal-equation": {
		solverMethod: "Ridge Regression Closed-Form Normal Equation (L2 Regularization)",
		regularization: "lambda * I added to Gram matrix X^T X (lambda >= 0)",
		formula: "theta = (X^T X + lambda * I)^(-1) X^T y",
		conventions: "lambda is read from input line 1",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["Ridge penalty: lambda * I", "Closed-form: (X^T X + lambda*I)^(-1) X^T y"],
	},
	"lr-weighted-least-squares-normal-equation": {
		solverMethod: "Weighted Least Squares Matrix Normal Equation",
		formula: "theta = (X^T W X)^(-1) X^T W y",
		conventions: "W is diagonal matrix of positive weights",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["W is diagonal matrix of weights", "theta = (X^T W X)^(-1) X^T W y"],
	},
	"lr-hat-matrix-projection": {
		solverMethod: "Orthogonal Projection Hat Matrix Computation",
		formula: "H = X (X^T X)^(-1) X^T, y_hat = H * y",
		conventions: "N x N symmetric, idempotent projection matrix",
		outputPrecision: "N predicted values y_hat formatted to 4 decimal places",
		extraConstraints: ["Hat matrix H = X (X^T X)^(-1) X^T", "Output: y_hat = H * y"],
	},
	"lr-residual-maker-matrix": {
		solverMethod: "Residual Maker (Annihilator) Matrix Computation",
		formula: "M = I - H = I - X (X^T X)^(-1) X^T, e = M * y",
		conventions: "Projects y onto orthogonal complement of column space of X",
		outputPrecision: "N residuals formatted to 4 decimal places",
		extraConstraints: ["M = I - X (X^T X)^(-1) X^T", "Output: residuals e = M * y"],
	},
	"lr-loocv-ridge-analytical-shortcut": {
		solverMethod: "Analytical Leave-One-Out Cross-Validation (LOOCV) for Ridge",
		formula: "LOOCV_MSE = (1/N) * sum(((y_i - y_hat_i) / (1 - H_ii))^2)",
		conventions: "H = X (X^T X + lambda*I)^(-1) X^T",
		outputPrecision: "Single real number formatted to 4 decimal places",
		extraConstraints: ["Analytical LOOCV: e_i / (1 - H_ii)", "Output: mean squared LOOCV error"],
	},
	"lr-recursive-least-squares-covariance-update": {
		solverMethod: "Recursive Least Squares (RLS) Online Covariance Update",
		formula: "P_{t+1} = P_t - (P_t * x * x^T * P_t) / (1 + x^T * P_t * x)",
		conventions: "Sherman-Morrison rank-1 inverse update with forgetting factor lambda = 1.0",
		outputPrecision: "D x D updated covariance matrix formatted to 4 decimal places",
		extraConstraints: ["Sherman-Morrison inverse update", "Forgetting factor lambda = 1.0"],
	},
	"lr-cholesky-normal-equation-solver": {
		solverMethod: "Cholesky Decomposition Normal Equation Solver",
		formula: "X^T X = L L^T (L is lower triangular), solve L z = X^T y, then L^T theta = z",
		conventions: "Gram matrix X^T X is symmetric positive definite",
		outputPrecision: "D parameters formatted to 4 decimal places",
		extraConstraints: ["X^T X = L L^T", "Forward & back substitution via L"],
	},
	"lr-qr-decomposition-ols": {
		solverMethod: "QR Decomposition Ordinary Least Squares Solver",
		formula: "X = Q R (Q is orthogonal, R is upper triangular), solve R * theta = Q^T * y",
		conventions: "Back-substitution on upper triangular matrix R",
		outputPrecision: "D parameters formatted to 4 decimal places",
		extraConstraints: ["X = Q R", "Back substitution: R * theta = Q^T * y"],
	},
	"lr-frisch-waugh-lovell-theorem": {
		solverMethod: "Frisch-Waugh-Lovell (FWL) Partialling-Out Regression",
		formula: "Project out X_1 from both X_2 and y: M_1 = I - X_1 (X_1^T X_1)^(-1) X_1^T, then theta_2 = (X_2^T M_1 X_2)^(-1) X_2^T M_1 y",
		conventions: "Subvector theta_2 matches full multivariate regression coefficient",
		outputPrecision: "theta_2 weights formatted to 4 decimal places",
		extraConstraints: ["FWL orthogonal projection", "Output: theta_2 coefficients"],
	},
	"lr-tikhonov-general-regularization": {
		solverMethod: "Generalized Tikhonov Regularization Normal Equation",
		formula: "theta = (X^T X + Gamma^T Gamma)^(-1) X^T y",
		conventions: "Gamma is user-specified regularization matrix",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["Regularization matrix Gamma", "theta = (X^T X + Gamma^T Gamma)^(-1) X^T y"],
	},
	"lr-principal-component-regression-rank1": {
		solverMethod: "Rank-1 Principal Component Regression (PCR)",
		formula: "Project X onto top eigenvector v_1 of X^T X: z = X * v_1, fit y = gamma * z, recover theta = gamma * v_1",
		conventions: "Unit-norm principal component vector ||v_1||_2 = 1",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["Rank-1 PCR projection", "||v_1|| = 1"],
	},
	"lr-generalized-least-squares-correlated-errors": {
		solverMethod: "Generalized Least Squares (GLS) with AR(1) Correlated Errors",
		formula: "theta = (X^T Omega^(-1) X)^(-1) X^T Omega^(-1) y, where Omega_{ij} = rho^|i - j|",
		conventions: "Autocorrelation parameter rho read from input",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["Covariance Omega_{ij} = rho^|i - j|", "theta = (X^T Omega^(-1) X)^(-1) X^T Omega^(-1) y"],
	},
	"lr-bgd-fixed-iterations": {
		solverMethod: "Batch Gradient Descent (BGD) with Fixed Iteration Count",
		initialParams: "w_0 = [0, 0, ..., 0] (vector of length D)",
		learningRate: "alpha = 0.05 (fixed)",
		iterations: "max_iter = 50 iterations (exact)",
		formula: "grad = (1/N) * X^T * (X * w - y), w_{t+1} = w_t - alpha * grad",
		conventions: "MSE Loss: L(w) = 1/(2N) * ||Xw - y||^2",
		outputPrecision: "D weights space-separated, 4 decimal places",
		extraConstraints: ["alpha = 0.05, max_iter = 50, w_0 = 0", "MSE Loss gradient: (1/N) * X^T (Xw - y)"],
	},
	"lr-bgd-gradient-norm-tolerance": {
		solverMethod: "Batch Gradient Descent with Gradient Norm Stopping Criterion",
		initialParams: "w_0 = [0, 0, ..., 0]",
		learningRate: "alpha = 0.02 (fixed)",
		iterations: "max_iter = 200 (hard cap)",
		tolerance: "eps = 1e-4 (stop when ||grad||_2 < eps)",
		formula: "grad = (1/N) * X^T * (X * w - y), w_{t+1} = w_t - alpha * grad",
		conventions: "Stop as soon as L2 norm of gradient falls below eps",
		outputPrecision: "Line 1: iterations executed (integer), Line 2: D weights (4 decimals)",
		extraConstraints: ["alpha = 0.02, eps = 1e-4, max_iter = 200, w_0 = 0", "Stop when ||grad||_2 < eps"],
	},
	"lr-bgd-loss-change-tolerance": {
		solverMethod: "Batch Gradient Descent with Objective Loss Change Tolerance",
		initialParams: "w_0 = [0, 0, ..., 0]",
		learningRate: "alpha = 0.03 (fixed)",
		iterations: "max_iter = 300 (hard cap)",
		tolerance: "eps = 1e-5 (stop when |L_t - L_{t-1}| < eps)",
		formula: "L(w) = (1 / (2*N)) * sum((Xw - y)^2)",
		conventions: "Evaluate loss change at end of each iteration",
		outputPrecision: "Line 1: iterations executed (integer), Line 2: D weights (4 decimals)",
		extraConstraints: ["alpha = 0.03, eps = 1e-5, max_iter = 300, w_0 = 0", "Stop when |L_t - L_{t-1}| < eps"],
	},
	"lr-bgd-classical-momentum": {
		solverMethod: "Batch Gradient Descent with Classical Polyak Momentum",
		initialParams: "w_0 = [0, 0, ..., 0], v_0 = [0, 0, ..., 0]",
		learningRate: "alpha = 0.02 (fixed)",
		iterations: "max_iter = 40 iterations (exact)",
		regularization: "beta = 0.9 (momentum decay parameter)",
		formula: "v_{t+1} = beta * v_t + alpha * grad, w_{t+1} = w_t - v_{t+1}",
		conventions: "grad = (1/N) * X^T (X * w_t - y)",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["alpha = 0.02, beta = 0.9, max_iter = 40, w_0 = 0, v_0 = 0", "v = beta*v + alpha*grad; w = w - v"],
	},
	"lr-bgd-nesterov-accelerated": {
		solverMethod: "Nesterov Accelerated Gradient (NAG) Descent",
		initialParams: "w_0 = [0, 0, ..., 0], v_0 = [0, 0, ..., 0]",
		learningRate: "alpha = 0.02 (fixed)",
		iterations: "max_iter = 40 iterations (exact)",
		regularization: "beta = 0.9 (momentum parameter)",
		formula: "w_look = w_t - beta * v_t, g = grad(w_look), v_{t+1} = beta * v_t + alpha * g, w_{t+1} = w_t - v_{t+1}",
		conventions: "Lookahead gradient evaluated at w_t - beta * v_t",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["alpha = 0.02, beta = 0.9, max_iter = 40, w_0 = 0, v_0 = 0", "Lookahead gradient at w - beta*v"],
	},
	"lr-bgd-adagrad-optimizer": {
		solverMethod: "Batch Gradient Descent with AdaGrad Optimizer",
		initialParams: "w_0 = [0, 0, ..., 0], G_0 = [0, 0, ..., 0]",
		learningRate: "eta = 0.5 (fixed)",
		iterations: "max_iter = 50 iterations (exact)",
		tolerance: "eps = 1e-8 (numerical stability denominator)",
		formula: "G_t = G_{t-1} + g_t^2, w_t = w_{t-1} - (eta / (sqrt(G_t) + eps)) * g_t",
		conventions: "Coordinate-wise accumulated squared gradients",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["eta = 0.5, eps = 1e-8, max_iter = 50, w_0 = 0, G_0 = 0", "w -= (eta / (sqrt(G) + eps)) * g"],
	},
	"lr-bgd-rmsprop-optimizer": {
		solverMethod: "Batch Gradient Descent with RMSprop Optimizer",
		initialParams: "w_0 = [0, 0, ..., 0], v_0 = [0, 0, ..., 0]",
		learningRate: "eta = 0.1 (fixed)",
		iterations: "max_iter = 50 iterations (exact)",
		regularization: "gamma = 0.9 (exponential moving average decay)",
		tolerance: "eps = 1e-8",
		formula: "v_t = gamma * v_{t-1} + (1 - gamma) * g_t^2, w_t = w_{t-1} - (eta / (sqrt(v_t) + eps)) * g_t",
		conventions: "Exponentially decaying average of squared gradients",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["eta = 0.1, gamma = 0.9, eps = 1e-8, max_iter = 50, w_0 = 0, v_0 = 0", "RMSprop update rule"],
	},
	"lr-bgd-adam-optimizer": {
		solverMethod: "Batch Gradient Descent with Adam Optimizer",
		initialParams: "w_0 = [0, 0, ..., 0], m_0 = [0, 0, ..., 0], v_0 = [0, 0, ..., 0]",
		learningRate: "alpha = 0.1 (fixed)",
		iterations: "max_iter = 50 iterations (exact)",
		regularization: "beta1 = 0.9, beta2 = 0.999",
		tolerance: "eps = 1e-8",
		formula: "m_t = beta1*m_{t-1} + (1-beta1)*g, v_t = beta2*v_{t-1} + (1-beta2)*g^2, m_hat = m_t / (1-beta1^t), v_hat = v_t / (1-beta2^t), w_t = w_{t-1} - alpha * m_hat / (sqrt(v_hat) + eps)",
		conventions: "Bias-corrected first and second moment estimates",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["alpha = 0.1, beta1 = 0.9, beta2 = 0.999, eps = 1e-8, max_iter = 50, w_0 = 0, m_0 = 0, v_0 = 0", "Full bias-corrected Adam steps"],
	},
	"lr-bgd-step-decay-schedule": {
		solverMethod: "BGD with Step-Decay Learning Rate Schedule",
		initialParams: "w_0 = [0, 0, ..., 0]",
		learningRate: "alpha_0 = 0.1, drop = 0.5, epochs_drop = 10",
		iterations: "total_iter = 40 iterations (exact)",
		formula: "alpha_t = alpha_0 * drop^(floor(t / epochs_drop)), w_{t+1} = w_t - alpha_t * grad",
		conventions: "t is 0-indexed iteration count (0 to 39)",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["alpha_0 = 0.1, drop = 0.5, epochs_drop = 10, total_iter = 40, w_0 = 0", "alpha_t = alpha_0 * drop^(floor(t / epochs_drop))"],
	},
	"lr-bgd-exponential-decay-schedule": {
		solverMethod: "BGD with Exponential Learning Rate Decay",
		initialParams: "w_0 = [0, 0, ..., 0]",
		learningRate: "alpha_0 = 0.1, decay rate k = 0.05",
		iterations: "total_iter = 40 iterations (exact)",
		formula: "alpha_t = alpha_0 * exp(-k * t), w_{t+1} = w_t - alpha_t * grad",
		conventions: "Continuous exponential decay at each iteration step t",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["alpha_0 = 0.1, k = 0.05, total_iter = 40, w_0 = 0", "alpha_t = alpha_0 * exp(-k * t)"],
	},
	"lr-bgd-backtracking-line-search": {
		solverMethod: "Backtracking Armijo Line Search Gradient Descent",
		initialParams: "w_0 = [0, 0, ..., 0], alpha_init = 1.0",
		iterations: "1 gradient step with adaptive step size",
		tolerance: "c = 0.1 (Armijo control parameter), rho = 0.5 (contraction factor)",
		formula: "Condition: L(w - alpha * g) <= L(w) - c * alpha * ||g||^2; else alpha := rho * alpha",
		conventions: "Max line search contractions = 10",
		outputPrecision: "Line 1: chosen alpha (4 decimals), Line 2: updated weights (4 decimals)",
		extraConstraints: ["alpha_init = 1.0, c = 0.1, rho = 0.5, max_contractions = 10", "Armijo condition check"],
	},
	"lr-bgd-gradient-clipping": {
		solverMethod: "BGD with L2 Gradient Norm Clipping",
		initialParams: "w_0 = [0, 0, ..., 0]",
		learningRate: "alpha = 0.05 (fixed)",
		iterations: "max_iter = 40 iterations (exact)",
		regularization: "clipping threshold c = 1.0",
		formula: "if ||grad||_2 > c: grad := grad * (c / ||grad||_2); w := w - alpha * grad",
		conventions: "Preserves gradient direction while capping maximum L2 norm",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["c = 1.0, alpha = 0.05, max_iter = 40, w_0 = 0", "Clip gradient if ||grad||_2 > c"],
	},
	"lr-bgd-ridge-regularized": {
		solverMethod: "Batch Gradient Descent with L2 Ridge Weight Decay",
		initialParams: "w_0 = [0, 0, ..., 0]",
		learningRate: "alpha = 0.05 (fixed)",
		iterations: "max_iter = 50 iterations (exact)",
		regularization: "lambda = 0.1 (Ridge penalty parameter)",
		formula: "grad = (1/N) * X^T (X*w - y) + lambda * w, w := w - alpha * grad",
		conventions: "Weight decay directly included in gradient vector",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["alpha = 0.05, lambda = 0.1, max_iter = 50, w_0 = 0", "grad = (1/N)*X^T(Xw - y) + lambda*w"],
	},
	"lr-bgd-early-stopping-validation": {
		solverMethod: "BGD with Validation Patience Early Stopping",
		initialParams: "w_0 = [0, 0, ..., 0]",
		learningRate: "alpha = 0.05 (fixed)",
		iterations: "max_iter = 50 (hard cap)",
		tolerance: "patience = 3 iterations without validation MSE improvement",
		formula: "val_mse = (1/N_val) * ||X_val * w - y_val||^2",
		conventions: "Stop when val_mse fails to strictly decrease for 3 consecutive steps",
		outputPrecision: "Line 1: stopped iteration (integer), Line 2: final weights (4 decimals)",
		extraConstraints: ["alpha = 0.05, patience = 3, max_iter = 50, w_0 = 0", "Stop if validation MSE does not improve for 3 steps"],
	},
	"lr-bgd-standardized-vs-unstandardized": {
		solverMethod: "BGD Convergence Comparison: Standardized vs Raw Features",
		initialParams: "w_0 = [0, 0, ..., 0]",
		learningRate: "alpha = 0.05 (fixed)",
		iterations: "max_iter = 20 iterations (exact)",
		conventions: "Z-score standardized with population std dev (divide by N)",
		outputPrecision: "Line 1: raw final MSE (4 decimals), Line 2: standardized final MSE (4 decimals)",
		extraConstraints: ["alpha = 0.05, max_iter = 20, w_0 = 0", "Population std dev for standardization"],
	},
	"lr-sgd-single-sample-update": {
		solverMethod: "Online Stochastic Gradient Descent (SGD) Single Sample Step",
		initialParams: "Read initial w from input line 2",
		learningRate: "alpha = 0.05 (fixed)",
		iterations: "1 single sample update on instance (x, y)",
		formula: "err = dot(w, x) - y, w_{new} = w - alpha * err * x",
		conventions: "Half squared error loss: L = 0.5 * (w^T x - y)^2",
		outputPrecision: "D weights space-separated, 4 decimal places",
		extraConstraints: ["alpha = 0.05, 1 update step", "w := w - alpha * (w^T x - y) * x"],
	},
	"lr-sgd-sequential-single-epoch": {
		solverMethod: "Sequential Single-Epoch Online SGD",
		initialParams: "w_0 = [0, 0, ..., 0]",
		learningRate: "alpha = 0.02 (fixed)",
		iterations: "1 epoch through all N samples in strictly given sequence",
		formula: "For each sample i: w := w - alpha * (x_i^T w - y_i) * x_i",
		conventions: "Process training samples in the exact order presented in input",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["alpha = 0.02, 1 epoch in sequential order, w_0 = 0", "Update after every single sample"],
	},
	"lr-sgd-decaying-step-size": {
		solverMethod: "Online SGD with Inverse-Time Learning Rate Decay",
		initialParams: "w_0 = [0, 0, ..., 0]",
		learningRate: "alpha_0 = 0.1, decay = 0.01",
		iterations: "1 pass over N samples (t = 1 to N)",
		formula: "alpha_t = alpha_0 / (1 + decay * t), w := w - alpha_t * (x_t^T w - y_t) * x_t",
		conventions: "Step t is 1-indexed (t = 1, 2, ..., N)",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["alpha_t = 0.1 / (1 + 0.01 * t), t starts at 1, w_0 = 0", "Sequential online updates"],
	},
	"lr-minibatch-gd-fixed-batch-size": {
		solverMethod: "Mini-Batch Gradient Descent with Fixed Batch Size B = 2",
		initialParams: "w_0 = [0, 0, ..., 0]",
		learningRate: "alpha = 0.05 (fixed)",
		iterations: "1 epoch partitioned into contiguous chunks of size B = 2",
		formula: "grad_B = (1/B) * X_B^T (X_B * w - y_B), w := w - alpha * grad_B",
		conventions: "Take consecutive pairs of samples without shuffling",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["Batch size B = 2, alpha = 0.05, w_0 = 0", "Sequential contiguous mini-batches"],
	},
	"lr-averaged-sgd-polyak-ruppert": {
		solverMethod: "Polyak-Ruppert Averaged Stochastic Gradient Descent (ASGD)",
		initialParams: "w_0 = [0, 0, ..., 0]",
		learningRate: "alpha = 0.05 (fixed)",
		iterations: "1 pass over N samples (T = N)",
		formula: "w_t = w_{t-1} - alpha * (x_t^T w_{t-1} - y_t) * x_t; final_w = (1/T) * sum_{t=1}^T w_t",
		conventions: "Average includes all post-update iterate vectors w_1 through w_T",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["alpha = 0.05, w_0 = 0", "Polyak average: (1/T) * sum(w_t)"],
	},
	"lr-sgd-online-ridge-weight-decay": {
		solverMethod: "Online SGD with L2 Weight Decay (Online Ridge)",
		initialParams: "w_0 = [0, 0, ..., 0]",
		learningRate: "alpha = 0.05 (fixed)",
		regularization: "lambda = 0.01 (weight decay coefficient)",
		formula: "w_{t+1} = (1 - alpha * lambda) * w_t - alpha * (x_t^T w_t - y_t) * x_t",
		conventions: "Decay applied simultaneously with gradient step",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["alpha = 0.05, lambda = 0.01, w_0 = 0", "w := (1 - alpha*lambda)*w - alpha*(x^T w - y)*x"],
	},
	"lr-passive-aggressive-regression": {
		solverMethod: "Passive-Aggressive Regression (PA-I Algorithm)",
		initialParams: "w_0 = [0, 0, ..., 0]",
		tolerance: "epsilon = 0.1 (insensitivity zone)",
		regularization: "C = 1.0 (aggressiveness parameter)",
		formula: "loss = max(0, |w^T x - y| - epsilon), tau = min(C, loss / ||x||^2), w := w + tau * sign(y - w^T x) * x",
		conventions: "No update if loss is zero (within epsilon tube)",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["epsilon = 0.1, C = 1.0, w_0 = 0", "PA-I step: tau = min(C, loss / ||x||^2)"],
	},
	"lr-minibatch-momentum": {
		solverMethod: "Mini-Batch SGD with Momentum",
		initialParams: "w_0 = [0, 0, ..., 0], v_0 = [0, 0, ..., 0]",
		learningRate: "alpha = 0.02 (fixed)",
		regularization: "beta = 0.9 (momentum parameter), batch size B = 2",
		formula: "v := beta * v + alpha * grad_B, w := w - v",
		conventions: "Batches of size 2 processed sequentially in order",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["B = 2, alpha = 0.02, beta = 0.9, w_0 = 0, v_0 = 0", "Mini-batch momentum updates"],
	},
	"lr-minibatch-rmsprop": {
		solverMethod: "Mini-Batch SGD with RMSprop",
		initialParams: "w_0 = [0, 0, ..., 0], v_0 = [0, 0, ..., 0]",
		learningRate: "eta = 0.05 (fixed)",
		regularization: "gamma = 0.9, batch size B = 2",
		tolerance: "eps = 1e-8",
		formula: "v := gamma * v + (1 - gamma) * grad_B^2, w := w - (eta / (sqrt(v) + eps)) * grad_B",
		conventions: "Coordinate-wise moving average of squared batch gradients",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["B = 2, eta = 0.05, gamma = 0.9, eps = 1e-8, w_0 = 0, v_0 = 0", "Mini-batch RMSprop updates"],
	},
	"lr-sgd-huber-loss-gradient": {
		solverMethod: "Online SGD with Robust Huber Loss Gradient",
		initialParams: "w_0 = [0, 0, ..., 0]",
		learningRate: "alpha = 0.05 (fixed)",
		tolerance: "delta = 1.0 (Huber transition threshold)",
		formula: "e = w^T x - y; if |e| <= delta: g = e * x; else: g = delta * sign(e) * x; w := w - alpha * g",
		conventions: "Linear gradient penalty for residuals beyond delta = 1.0",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["delta = 1.0, alpha = 0.05, w_0 = 0", "Huber loss gradient clipping"],
	},
	"lr-sgd-gradient-accumulation": {
		solverMethod: "SGD with Micro-Batch Gradient Accumulation",
		initialParams: "w_0 = [0, 0, ..., 0]",
		learningRate: "alpha = 0.05 (fixed)",
		iterations: "Accumulation steps K = 3 (update weights every 3 samples)",
		formula: "accum_grad += (x_i^T w - y_i) * x_i; every 3 samples: w := w - alpha * (accum_grad / 3), accum_grad := 0",
		conventions: "Averages gradient over micro-batches of size 3 before updating",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["Accumulation K = 3, alpha = 0.05, w_0 = 0", "Update weights every 3 samples with average gradient"],
	},
	"lr-barzilai-borwein-sgd": {
		solverMethod: "Barzilai-Borwein Adaptive Step Size Two-Point Gradient Step",
		formula: "s_{k-1} = w_k - w_{k-1}, y_{k-1} = g_k - g_{k-1}, alpha_BB = (s_{k-1}^T s_{k-1}) / (s_{k-1}^T y_{k-1}), w_{k+1} = w_k - alpha_BB * g_k",
		conventions: "Analytical spectral step length approximating inverse Hessian",
		outputPrecision: "Line 1: alpha_BB (4 decimals), Line 2: updated weights (4 decimals)",
		extraConstraints: ["Barzilai-Borwein step: s^T s / (s^T y)", "Output: alpha_BB and updated w"],
	},
	"lr-minibatch-gradient-variance": {
		solverMethod: "Mini-Batch Gradient Variance Diagnostic",
		conventions: "Compute population variance (divide by number of mini-batches M) across all coordinate gradients with batch size B = 2",
		formula: "Var(g_j) = (1/M) * sum_{m=1}^M (g_{m, j} - mean(g_j))^2",
		outputPrecision: "D variance values space-separated, 4 decimal places",
		extraConstraints: ["Batch size B = 2", "Population variance: divide by M"],
	},
	"lr-sgd-cosine-annealing-schedule": {
		solverMethod: "SGD with Cosine Annealing Learning Rate Schedule",
		initialParams: "w_0 = [0, 0, ..., 0]",
		learningRate: "alpha_min = 0.001, alpha_max = 0.1, T_max = N",
		formula: "alpha_t = alpha_min + 0.5 * (alpha_max - alpha_min) * (1 + cos(pi * t / T_max))",
		conventions: "Step t is 1-indexed (t = 1 to N)",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["alpha_min = 0.001, alpha_max = 0.1, T_max = N, w_0 = 0", "Cosine annealing decay formula"],
	},
	"lr-streaming-exponential-sgd": {
		solverMethod: "Streaming SGD with Exponential Memory Forgetting",
		initialParams: "w_0 = [0, 0, ..., 0]",
		learningRate: "alpha = 0.05 (fixed)",
		regularization: "gamma = 0.95 (exponential memory discounting factor)",
		formula: "w_{t+1} = gamma * w_t - alpha * (x_t^T (gamma * w_t) - y_t) * x_t",
		conventions: "Discounts previous parameter state by gamma before processing incoming stream sample",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["gamma = 0.95, alpha = 0.05, w_0 = 0", "Discount prior state: w := gamma * w - alpha * grad"],
	},
	"lr-lasso-soft-thresholding": {
		solverMethod: "Lasso Soft-Thresholding Operator S(z, lambda)",
		formula: "S(z, lambda) = sign(z) * max(0, |z| - lambda)",
		conventions: "Zero threshold region: if |z| <= lambda, result is 0.0000",
		outputPrecision: "N thresholded values space-separated, 4 decimal places",
		extraConstraints: ["S(z, lambda) = sign(z) * max(0, |z| - lambda)", "lambda read from input line 1"],
	},
	"lr-lasso-single-coordinate-update": {
		solverMethod: "Lasso Single Coordinate Descent Step",
		formula: "rho_j = x_j^T (y - X_{-j} w_{-j}), z_j = ||x_j||^2, w_j = S(rho_j, lambda/2) / z_j",
		conventions: "Updates single specified feature j while keeping others fixed",
		outputPrecision: "Updated scalar weight w_j formatted to 4 decimal places",
		extraConstraints: ["Update coordinate j using soft-thresholding", "w_j = S(rho_j, lambda/2) / z_j"],
	},
	"lr-lasso-coordinate-descent-cycles": {
		solverMethod: "Lasso Full Cyclic Coordinate Descent",
		initialParams: "w_0 = [0, 0, ..., 0]",
		iterations: "5 full cyclic sweeps over all D coordinates",
		regularization: "lambda = 0.5 (fixed)",
		formula: "In each cycle, update j = 0..D-1 sequentially: w_j := S(x_j^T (y - sum_{k!=j} x_k w_k), lambda/2) / ||x_j||^2",
		conventions: "Cyclic order from coordinate 0 to D-1",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["lambda = 0.5, 5 full cycles, w_0 = 0", "Cyclic coordinate updates"],
	},
	"lr-elasticnet-coordinate-descent": {
		solverMethod: "ElasticNet Coordinate Descent (L1 + L2 Regularization)",
		initialParams: "w_0 = [0, 0, ..., 0]",
		iterations: "5 full cycles over all D coordinates",
		regularization: "lambda = 0.5, l1_ratio = 0.5",
		formula: "w_j := S(rho_j, lambda * l1_ratio / 2) / (||x_j||^2 + lambda * (1 - l1_ratio))",
		conventions: "Combines L1 soft-thresholding numerator with L2 ridge denominator penalty",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["lambda = 0.5, l1_ratio = 0.5, 5 cycles, w_0 = 0", "ElasticNet coordinate update formula"],
	},
	"lr-nonnegative-least-squares-step": {
		solverMethod: "Non-Negative Least Squares (NNLS) Projected Gradient Step",
		initialParams: "w_0 = [0, 0, ..., 0]",
		learningRate: "alpha = 0.05 (fixed)",
		iterations: "50 iterations (exact)",
		formula: "grad = (1/N) * X^T (X * w - y), w := max(0, w - alpha * grad)",
		conventions: "Coordinate-wise projection onto non-negative orthant w_j >= 0",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["alpha = 0.05, 50 iterations, w_0 = 0", "Projected gradient: w := max(0, w - alpha*grad)"],
	},
	"lr-ridge-shrinkage-svd-coordinates": {
		solverMethod: "Ridge Shrinkage Factor in SVD Coordinate Basis",
		formula: "shrinkage_i = sigma_i^2 / (sigma_i^2 + lambda)",
		conventions: "sigma_i are singular values of X, lambda read from input line 1",
		outputPrecision: "D shrinkage factors space-separated, 4 decimal places",
		extraConstraints: ["shrinkage_i = sigma_i^2 / (sigma_i^2 + lambda)", "Output formatted to 4 decimals"],
	},
	"lr-ridge-effective-degrees-of-freedom": {
		solverMethod: "Ridge Effective Degrees of Freedom df(lambda)",
		formula: "df(lambda) = sum_{i=1}^D (sigma_i^2 / (sigma_i^2 + lambda))",
		conventions: "Equivalent trace of hat matrix tr(H(lambda))",
		outputPrecision: "Single real number formatted to 4 decimal places",
		extraConstraints: ["df(lambda) = sum(sigma_i^2 / (sigma_i^2 + lambda))", "Output formatted to 4 decimals"],
	},
	"lr-lasso-sparsity-counter": {
		solverMethod: "Lasso Feature Sparsity & Active Set Diagnostic",
		tolerance: "Zero threshold eps = 1e-5 (count |w_j| <= eps as zero)",
		formula: "sparsity = count(|w_j| <= 1e-5), active_count = D - sparsity",
		conventions: "Treat absolute weights <= 1e-5 as structurally sparse zeros",
		outputPrecision: "Two integers: non_zero_count zero_count",
		extraConstraints: ["Zero threshold: |w_j| <= 1e-5", "Output: active_count zero_count"],
	},
	"lr-adaptive-lasso-weights": {
		solverMethod: "Adaptive Lasso Penalty Weights Computation",
		tolerance: "eps = 1e-6 (numerical safeguard)",
		formula: "penalty_weight_j = 1 / (|w_ols_j| + 1e-6)",
		conventions: "Inversely weights L1 penalties by initial OLS coefficient magnitude",
		outputPrecision: "D penalty weights space-separated, 4 decimal places",
		extraConstraints: ["weight_j = 1 / (|w_ols_j| + 1e-6)", "Output: D penalty weights"],
	},
	"lr-fused-lasso-total-variation-penalty": {
		solverMethod: "Fused Lasso Total Variation (TV) Penalty Evaluation",
		formula: "TV(w) = sum_{j=1}^{D-1} |w_{j+1} - w_j|",
		conventions: "Measures 1D smoothness between adjacent feature coefficients",
		outputPrecision: "Single real number formatted to 4 decimal places",
		extraConstraints: ["TV = sum |w_{j+1} - w_j|", "Output: TV formatted to 4 decimals"],
	},
	"lr-elasticnet-mixing-parameter": {
		solverMethod: "ElasticNet Penalty Decomposition Evaluation",
		formula: "L1_pen = lambda * l1_ratio * sum(|w_j|), L2_pen = 0.5 * lambda * (1 - l1_ratio) * sum(w_j^2), Total = L1_pen + L2_pen",
		conventions: "lambda and l1_ratio read from input line 1",
		outputPrecision: "Three real numbers: L1_pen L2_pen Total formatted to 4 decimal places",
		extraConstraints: ["L1 penalty: lambda * l1_ratio * ||w||_1", "L2 penalty: 0.5 * lambda * (1 - l1_ratio) * ||w||_2^2"],
	},
	"lr-group-lasso-block-norm": {
		solverMethod: "Group Lasso Block Penalty Evaluation (L2,1 Norm)",
		formula: "Block_norm = sum_{g in Groups} sqrt(sum_{j in g} w_j^2)",
		conventions: "Euclidean norm of each disjoint coordinate group summed across groups",
		outputPrecision: "Single real number formatted to 4 decimal places",
		extraConstraints: ["sum sqrt(sum_{j in g} w_j^2)", "Output formatted to 4 decimals"],
	},
	"lr-ridge-regularization-path": {
		solverMethod: "Ridge Regularization Path Multi-Lambda Normal Equation Solver",
		formula: "For each lambda_k: theta(lambda_k) = (X^T X + lambda_k * I)^(-1) X^T y",
		conventions: "Solves exact ridge normal equations for each lambda sequentially",
		outputPrecision: "K lines, each line containing D weights formatted to 4 decimal places",
		extraConstraints: ["Solve for each lambda in input", "theta = (X^T X + lambda*I)^(-1) X^T y"],
	},
	"lr-lars-first-direction-step": {
		solverMethod: "Least Angle Regression (LARS) Initial Active Feature Identification",
		formula: "Compute correlations c_j = |x_j^T y| / ||x_j||_2; active feature j* = argmax c_j",
		conventions: "Break ties by selecting the lower feature index",
		outputPrecision: "Integer index of active feature j* (0-indexed)",
		extraConstraints: ["c_j = |x_j^T y| / ||x_j||_2", "Break ties by lower index (0-indexed)"],
	},
	"lr-scad-thresholding-operator": {
		solverMethod: "SCAD (Smoothly Clipped Absolute Deviation) Non-Convex Thresholding",
		regularization: "Tuning parameter a = 3.7 (standard SCAD constant)",
		formula: "If |z| <= 2*lambda: S(z, lambda); else if |z| <= a*lambda: ((a-1)*z - sign(z)*a*lambda) / (a - 2); else: z",
		conventions: "Fixed constant a = 3.7",
		outputPrecision: "N thresholded values space-separated, 4 decimal places",
		extraConstraints: ["SCAD constant a = 3.7", "Output: N thresholded values to 4 decimals"],
	},
	"lr-huber-loss-evaluation": {
		solverMethod: "Huber Robust Loss Evaluation",
		tolerance: "delta = 1.0 (or read from input line 1)",
		formula: "For residual e = y - y_hat: if |e| <= delta: 0.5 * e^2; else: delta * (|e| - 0.5 * delta); return mean",
		conventions: "Quadratic for small errors, linear for outlier errors",
		outputPrecision: "Single real number formatted to 4 decimal places",
		extraConstraints: ["Mean Huber loss", "delta from input"],
	},
	"lr-quantile-pinball-loss": {
		solverMethod: "Quantile Regression Pinball (Check) Loss",
		conventions: "Quantile level tau = 0.75 (or read from input line 1)",
		formula: "L_tau(u) = max(tau * u, (tau - 1) * u) where u = y - y_hat; return mean",
		outputPrecision: "Single real number formatted to 4 decimal places",
		extraConstraints: ["Pinball loss L_tau(y - y_hat)", "tau from input"],
	},
	"lr-median-lad-subgradient-step": {
		solverMethod: "Least Absolute Deviations (LAD / Median Regression) Subgradient Descent",
		initialParams: "Read initial w from input",
		learningRate: "alpha = 0.05 (fixed)",
		iterations: "1 subgradient step",
		formula: "subgrad = -(1/N) * sum sign(y_i - x_i^T w) * x_i; w := w - alpha * subgrad",
		conventions: "sign(0) = 0",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["alpha = 0.05, 1 step", "Subgradient: -(1/N) * sum sign(y - w^T x) * x"],
	},
	"lr-theil-sen-median-slope": {
		solverMethod: "Theil-Sen Robust Median Slope and Intercept Estimator",
		formula: "Slope = median of all pairwise slopes (y_j - y_i) / (x_j - x_i) for x_j != x_i; Intercept = median of (y_i - slope * x_i)",
		conventions: "Use exact median (for even length, average of middle two)",
		outputPrecision: "Exactly 4 decimal places: slope intercept",
		extraConstraints: ["Pairwise slopes median", "Intercept = median(y - slope * x)"],
	},
	"lr-ransac-single-iteration": {
		solverMethod: "RANSAC Inlier Counting for Hypothesized Model",
		formula: "Residual |y_i - (beta_0 + beta_1 * x_i)| <= threshold",
		conventions: "threshold read from input line 1",
		outputPrecision: "Integer count of inliers",
		extraConstraints: ["Inlier condition: |y - (b0 + b1*x)| <= threshold", "Output: integer inlier count"],
	},
	"lr-irls-huber-single-iteration": {
		solverMethod: "Iteratively Reweighted Least Squares (IRLS) Huber Weighting Step",
		tolerance: "delta = 1.0 (Huber threshold)",
		formula: "For residual e_i = y_i - x_i^T w: weight w_i = 1 / max(1.0, |e_i| / delta)",
		conventions: "Computes observation weights for reweighted least squares",
		outputPrecision: "N weights space-separated, 4 decimal places",
		extraConstraints: ["w_i = 1 / max(1, |e_i| / delta)", "delta = 1.0"],
	},
	"lr-tukey-bisquare-weights": {
		solverMethod: "Tukey's Bisquare (Biweight) M-Estimator Weight Function",
		regularization: "Tuning constant c = 4.685",
		formula: "u = e / c; if |u| < 1: w(e) = (1 - u^2)^2; else: 0.0000",
		conventions: "Completely zeros out residuals exceeding tuning threshold c",
		outputPrecision: "N weights space-separated, 4 decimal places",
		extraConstraints: ["Tuning constant c = 4.685", "w = (1 - (e/c)^2)^2 if |e| < c else 0"],
	},
	"lr-least-trimmed-squares-subset-mse": {
		solverMethod: "Least Trimmed Squares (LTS) Trimmed MSE Evaluation",
		formula: "Sort squared residuals r_i^2 in ascending order, compute mean of smallest h = floor(0.75 * N) residuals",
		conventions: "Trim fraction 75% smallest residuals",
		outputPrecision: "Single real number formatted to 4 decimal places",
		extraConstraints: ["h = floor(0.75 * N)", "Mean of h smallest squared residuals"],
	},
	"lr-quantile-subgradient-step-tau90": {
		solverMethod: "Quantile Regression Subgradient Step at tau = 0.90",
		initialParams: "Read initial w from input",
		learningRate: "alpha = 0.05 (fixed)",
		iterations: "1 subgradient step",
		formula: "u_i = y_i - x_i^T w; subgrad = -(1/N) * sum (if u_i > 0: 0.90 else: -0.10) * x_i; w := w - alpha * subgrad",
		conventions: "Quantile check function subgradient at tau = 0.90",
		outputPrecision: "D weights formatted to 4 decimal places",
		extraConstraints: ["tau = 0.90, alpha = 0.05, 1 step", "Pinball subgradient step"],
	},
	"lr-welsch-m-estimator-weights": {
		solverMethod: "Welsch M-Estimator Exponential Weight Function",
		regularization: "Tuning constant c = 2.985",
		formula: "w(e) = exp(-(e / c)^2)",
		conventions: "Smooth exponential decay weight for robust regression",
		outputPrecision: "N weights space-separated, 4 decimal places",
		extraConstraints: ["Tuning constant c = 2.985", "w = exp(-(e / c)^2)"],
	},
	"lr-metrics-mse-and-rmse": {
		solverMethod: "Mean Squared Error & Root Mean Squared Error Evaluation",
		formula: "MSE = (1/N) * sum((y_i - y_hat_i)^2), RMSE = sqrt(MSE)",
		conventions: "Unweighted population residuals",
		outputPrecision: "Exactly 4 decimal places: MSE RMSE",
		extraConstraints: ["MSE = (1/N) * sum(e^2)", "RMSE = sqrt(MSE)"],
	},
	"lr-metrics-mae-and-mape": {
		solverMethod: "Mean Absolute Error & Mean Absolute Percentage Error",
		formula: "MAE = (1/N) * sum(|y - y_hat|), MAPE = (100/N) * sum(|(y - y_hat) / y|)",
		conventions: "y_i != 0 for percentage error calculation",
		outputPrecision: "Exactly 4 decimal places: MAE MAPE",
		extraConstraints: ["MAE = (1/N) * sum(|e|)", "MAPE = (100/N) * sum(|e / y|)"],
	},
	"lr-metrics-r-squared": {
		solverMethod: "Coefficient of Determination (R^2 Score)",
		formula: "R^2 = 1 - (SS_res / SS_tot), where SS_res = sum((y - y_hat)^2), SS_tot = sum((y - mean(y))^2)",
		conventions: "If SS_tot == 0: return 1.0000 if SS_res == 0 else 0.0000",
		outputPrecision: "Single real number formatted to 4 decimal places",
		extraConstraints: ["R^2 = 1 - (SS_res / SS_tot)", "Handle SS_tot == 0 edge case"],
	},
	"lr-metrics-adjusted-r-squared": {
		solverMethod: "Adjusted R-Squared with Model Degrees of Freedom Correction",
		formula: "R^2_adj = 1 - (1 - R^2) * ((N - 1) / (N - p - 1))",
		conventions: "p is number of predictors (features excluding intercept)",
		outputPrecision: "Single real number formatted to 4 decimal places",
		extraConstraints: ["R^2_adj = 1 - (1 - R^2)*(N - 1)/(N - p - 1)", "p = number of features"],
	},
	"lr-metrics-sum-of-squares-anova": {
		solverMethod: "ANOVA Sum of Squares Decomposition (TSS, ESS, RSS)",
		formula: "TSS = sum((y - mean(y))^2), ESS = sum((y_hat - mean(y))^2), RSS = sum((y - y_hat)^2)",
		conventions: "TSS = ESS + RSS identity",
		outputPrecision: "Three real numbers: TSS ESS RSS formatted to 4 decimal places",
		extraConstraints: ["TSS = sum((y - y_bar)^2)", "ESS = sum((y_hat - y_bar)^2)", "RSS = sum((y - y_hat)^2)"],
	},
	"lr-diagnostics-leverage-hat-values": {
		solverMethod: "Leverage Hat Matrix Diagonal Values (h_ii)",
		formula: "h_ii = x_i^T (X^T X)^(-1) x_i",
		conventions: "Measures distance of observation from feature space centroid",
		outputPrecision: "N leverage values space-separated, 4 decimal places",
		extraConstraints: ["h_ii = diag(X (X^T X)^(-1) X^T)", "Output: N leverage values"],
	},
	"lr-diagnostics-studentized-residuals": {
		solverMethod: "Internally Studentized Residuals Diagnostic",
		formula: "r_i = e_i / (s * sqrt(1 - h_ii)), where s = sqrt(RSS / (N - p))",
		conventions: "p is number of columns in X",
		outputPrecision: "N studentized residuals space-separated, 4 decimal places",
		extraConstraints: ["s = sqrt(RSS / (N - p))", "r_i = e_i / (s * sqrt(1 - h_ii))"],
	},
	"lr-diagnostics-cooks-distance": {
		solverMethod: "Cook's Distance Influential Observation Diagnostic",
		formula: "D_i = (e_i^2 / (p * s^2)) * (h_ii / (1 - h_ii)^2)",
		conventions: "Combines residual size and leverage into single influence metric",
		outputPrecision: "N Cook's distance values space-separated, 4 decimal places",
		extraConstraints: ["Cook's D formula", "Output: N values formatted to 4 decimals"],
	},
	"lr-diagnostics-vif-multicollinearity": {
		solverMethod: "Variance Inflation Factor (VIF) Multicollinearity Metric",
		formula: "VIF_j = 1 / (1 - R_j^2) where R_j^2 is coefficient of determination regressing feature j on other features",
		conventions: "Cap at 999.9999 if R_j^2 >= 0.99999",
		outputPrecision: "D VIF values space-separated, 4 decimal places",
		extraConstraints: ["VIF_j = 1 / (1 - R_j^2)", "Multicollinearity diagnostic"],
	},
	"lr-diagnostics-durbin-watson-stat": {
		solverMethod: "Durbin-Watson Autocorrelation Statistic",
		formula: "DW = sum_{t=2}^N (e_t - e_{t-1})^2 / sum_{t=1}^N e_t^2",
		conventions: "Evaluates first-order autocorrelation of residuals in time sequence",
		outputPrecision: "Single real number formatted to 4 decimal places",
		extraConstraints: ["DW = sum(e_t - e_{t-1})^2 / sum(e_t^2)", "Output formatted to 4 decimals"],
	},
	"lr-metrics-akaike-information-criterion": {
		solverMethod: "Akaike Information Criterion (AIC & AICc)",
		formula: "AIC = N * ln(RSS / N) + 2*k, AICc = AIC + (2*k*(k + 1)) / (N - k - 1)",
		conventions: "k is total model parameters including intercept and error variance",
		outputPrecision: "Two real numbers: AIC AICc formatted to 4 decimal places",
		extraConstraints: ["AIC = N * ln(RSS/N) + 2k", "AICc sample size correction"],
	},
	"lr-metrics-bayesian-information-criterion": {
		solverMethod: "Bayesian Information Criterion (BIC / Schwarz Criterion)",
		formula: "BIC = N * ln(RSS / N) + k * ln(N)",
		conventions: "k is total number of parameters",
		outputPrecision: "Single real number formatted to 4 decimal places",
		extraConstraints: ["BIC = N * ln(RSS/N) + k * ln(N)", "Output formatted to 4 decimals"],
	},
	"lr-diagnostics-breusch-pagan-stat": {
		solverMethod: "Breusch-Pagan Test Statistic for Heteroscedasticity",
		formula: "Fit OLS residuals squared e_i^2 on X, LM statistic = N * R_aux^2",
		conventions: "R_aux^2 is coefficient of determination of auxiliary regression",
		outputPrecision: "Single real number formatted to 4 decimal places",
		extraConstraints: ["LM = N * R_aux^2", "Auxiliary regression on e^2"],
	},
	"lr-metrics-maximum-residual-error": {
		solverMethod: "Maximum Residual Error & Median Absolute Error",
		formula: "Max_Error = max(|y_i - y_hat_i|), Med_AE = median(|y_i - y_hat_i|)",
		conventions: "Worst-case error and median robust error",
		outputPrecision: "Two real numbers: Max_Error Med_AE formatted to 4 decimal places",
		extraConstraints: ["Max_Error = max(|e|)", "Med_AE = median(|e|)"],
	},
	"lr-metrics-mean-bias-error": {
		solverMethod: "Mean Bias Error (MBE) & Fractional Bias",
		formula: "MBE = (1/N) * sum(y_hat_i - y_i), FB = 2 * (mean(y_hat) - mean(y)) / (mean(y_hat) + mean(y))",
		conventions: "Directional bias indicating systematic over- or under-estimation",
		outputPrecision: "Two real numbers: MBE FB formatted to 4 decimal places",
		extraConstraints: ["MBE = (1/N) * sum(y_hat - y)", "Fractional bias FB"],
	},
};
