import { ProblemHyperparameterSpec } from "../hyperparameter-renderer";

export const mlProblemSpecs: Record<string, ProblemHyperparameterSpec> = {
	"predict-fuel-prices-bomboclat-logistics": {
		solverMethod: "Multiple Linear Regression via Exact OLS Normal Equation",
		formula: "theta = (X^T X)^(-1) X^T y",
		conventions: "Prepend column of 1s to feature matrix X for intercept theta0",
		outputPrecision: "Line 1: n+1 theta parameters, Line 2: t test scenario predictions (all 4 decimal places)",
		extraConstraints: ["Exact OLS Normal Equation: theta = (X^T X)^(-1) X^T y", "Intercept theta0 corresponds to prepended column of 1s"],
	},
	"hyperion-solar-power-forecasting": {
		solverMethod: "Analytical Simple Linear Regression (Bivariate OLS)",
		formula: "m = sum((x_i - mean(x))*(y_i - mean(y))) / sum((x_i - mean(x))^2), b = mean(y) - m * mean(x)",
		conventions: "Test prediction: y_pred = m * x_test + b",
		outputPrecision: "Line 1: slope intercept, Line 2: predicted_y (all 4 decimal places)",
		extraConstraints: ["Simple OLS closed form formulas", "y_pred = m * x_test + b"],
	},
	"aegis-housing-valuation-ridge": {
		solverMethod: "1D Analytical Ridge Regression (L2 Regularization)",
		regularization: "lambda >= 0 read from input line 1",
		formula: "w = sum((x_i - mean(x))*(y_i - mean(y))) / (sum((x_i - mean(x))^2) + lambda), b = mean(y) - w * mean(x)",
		conventions: "Unpenalized intercept b computed from centered means",
		outputPrecision: "w b space-separated, 4 decimal places",
		extraConstraints: ["Unpenalized intercept b = mean(y) - w * mean(x)", "w = cov(x,y) / (var(x) + lambda)"],
	},
	"aero-turbine-efficiency-polynomial": {
		solverMethod: "Degree-2 Polynomial Linear Curve Fitting via 3x3 Normal Equations",
		formula: "Solve for [a, b, c] in y = a*x^2 + b*x + c",
		conventions: "Columns correspond to powers [x^2, x, 1]",
		outputPrecision: "a b c space-separated, 4 decimal places",
		extraConstraints: ["Quadratic polynomial: y = a*x^2 + b*x + c", "Output order: a b c"],
	},
	"quantum-fintech-lasso-selection": {
		solverMethod: "Lasso Soft-Thresholding Operator S(z, gamma)",
		tolerance: "gamma >= 0 read from input line 1",
		formula: "if z > gamma: z - gamma; else if z < -gamma: z + gamma; else: 0.0000",
		conventions: "Applies coordinate-wise to unregularized weights",
		outputPrecision: "N thresholded weights, 4 decimal places",
		extraConstraints: ["Soft thresholding: sign(z) * max(0, |z| - gamma)", "gamma from input"],
	},
	"titan-mining-ore-yield-sgd": {
		solverMethod: "Online Stochastic Gradient Descent (SGD)",
		initialParams: "theta_0 read from input line 2 (vector of length D)",
		learningRate: "alpha read from input line 1",
		iterations: "Process exactly K incoming instances sequentially",
		formula: "theta := theta - alpha * (dot(theta, x) - y) * x",
		conventions: "Half squared error loss: L = 0.5 * (theta^T x - y)^2",
		outputPrecision: "D updated weights, 4 decimal places",
		extraConstraints: ["Online sequential SGD updates", "Learning rate alpha from input line 1"],
	},
	"solaris-wind-farm-mae-vs-mse": {
		solverMethod: "Regression Loss Metrics Evaluation (MSE, RMSE, MAE)",
		formula: "MSE = (1/N)*sum((y - y_hat)^2), RMSE = sqrt(MSE), MAE = (1/N)*sum(|y - y_hat|)",
		conventions: "Unweighted population error metrics",
		outputPrecision: "MSE RMSE MAE space-separated, 4 decimal places",
		extraConstraints: ["MSE = (1/N) * sum((y - y_hat)^2)", "RMSE = sqrt(MSE)", "MAE = (1/N) * sum(|y - y_hat|)"],
	},
	"deep-sea-pressure-r-squared": {
		solverMethod: "Coefficient of Determination (R^2 Score)",
		formula: "R^2 = 1 - (SS_res / SS_tot), SS_res = sum((y - y_hat)^2), SS_tot = sum((y - mean(y))^2)",
		conventions: "If SS_tot == 0: return 1.0000 if SS_res == 0 else 0.0000",
		outputPrecision: "Single real number, 4 decimal places",
		extraConstraints: ["R^2 = 1 - (SS_res / SS_tot)", "Baseline mean model yields 0.0000"],
	},
	"chronos-server-latency-huber-loss": {
		solverMethod: "Mean Huber Robust Loss Evaluation",
		tolerance: "delta > 0 read from input line 1",
		formula: "a = |y - y_hat|; if a <= delta: 0.5 * a^2; else: delta * (a - 0.5 * delta); return mean",
		conventions: "Transition boundary at absolute residual delta",
		outputPrecision: "Single real number, 4 decimal places",
		extraConstraints: ["Mean Huber loss", "Threshold delta from input line 1"],
	},
	"glacier-melt-rate-weighted-least-squares": {
		solverMethod: "Weighted Least Squares (WLS) Analytical Solver",
		formula: "m = (sum(w)*sum(w*x*y) - sum(w*x)*sum(w*y)) / (sum(w)*sum(w*x^2) - (sum(w*x))^2), b = (sum(w*y) - m*sum(w*x)) / sum(w)",
		conventions: "Weights w_i are positive real numbers from input line 4",
		outputPrecision: "m b space-separated, 4 decimal places",
		extraConstraints: ["Analytical WLS formula", "Weights w_i from input line 4"],
	},
	"cyber-sentinel-malware-logistic": {
		solverMethod: "Logistic Regression Sigmoid Probability & Decision Boundary",
		formula: "logit z = b + sum(w_j * x_j), p = 1 / (1 + exp(-z)), label = 1 if p >= 0.5 else 0",
		conventions: "Binary classification threshold at probability p = 0.5",
		outputPrecision: "T lines, each: probability label (probability to 4 decimal places)",
		extraConstraints: ["Sigmoid: 1 / (1 + exp(-z))", "Decision boundary: p >= 0.5 -> class 1, else 0"],
	},
	"astral-spectral-star-knn": {
		solverMethod: "k-Nearest Neighbors (k-NN) Classification",
		formula: "dist(u, v) = sqrt(sum((u_d - v_d)^2))",
		conventions: "Majority vote among K closest neighbors. Tie-breaking: choose class of closest neighbor among tied classes",
		outputPrecision: "Single integer: predicted class_id",
		extraConstraints: ["Euclidean distance metric", "Tie break by class of closest neighbor"],
	},
	"bio-pathogen-gaussian-naive-bayes": {
		solverMethod: "Gaussian Naive Bayes Classifier",
		tolerance: "eps = 1e-9 added to variance for numerical stability",
		formula: "Prior P(c) = N_c / N; Gaussian likelihood N(x_d | mu_{c,d}, sigma^2_{c,d}); score = ln P(c) + sum ln N(x_d | mu_{c,d}, sigma^2_{c,d})",
		conventions: "Use population variance: sigma^2 = (1/N_c) * sum((x - mu)^2) (divide by N_c, not N_c - 1)",
		outputPrecision: "Single integer: predicted class_id with maximum log-posterior",
		extraConstraints: ["Population variance: divide by N_c", "eps = 1e-9 variance floor"],
	},
	"credit-guardian-decision-tree-entropy": {
		solverMethod: "Shannon Entropy Evaluation for Decision Tree Splitting",
		formula: "H(S) = -sum_{c} p_c * log2(p_c) where p_c = count(c) / N",
		conventions: "Convention: if p_c == 0, then 0 * log2(0) = 0",
		outputPrecision: "Single real number, 4 decimal places",
		extraConstraints: ["Base-2 logarithm: log2", "0 * log2(0) = 0"],
	},
	"pharma-compound-gini-impurity": {
		solverMethod: "Gini Impurity Evaluation for Decision Trees (CART)",
		formula: "Gini(S) = 1 - sum_{c} p_c^2 where p_c = count(c) / N",
		conventions: "Pure node yields Gini = 0.0000",
		outputPrecision: "Single real number, 4 decimal places",
		extraConstraints: ["Gini = 1 - sum(p_c^2)", "Output formatted to 4 decimals"],
	},
	"draco-fraud-detector-precision-recall": {
		solverMethod: "Binary Confusion Matrix & Classification Metrics",
		formula: "TP, FP, FN, TN; Precision = TP/(TP+FP); Recall = TP/(TP+FN); F1 = 2*Prec*Rec/(Prec+Rec)",
		conventions: "If denominator is 0, assign metric = 0.0000",
		outputPrecision: "Line 1: TP FP FN TN (integers), Line 2: Precision Recall F1 (4 decimal places)",
		extraConstraints: ["Zero division defaults to 0.0000", "Output: counts on line 1, metrics on line 2"],
	},
	"sentinel-intrusion-perceptron": {
		solverMethod: "Rosenblatt's Perceptron Learning Algorithm",
		initialParams: "w_0 = [0, 0, ..., 0] (vector of length D)",
		learningRate: "eta = 1 (fixed integer step)",
		iterations: "E full epochs through N training samples in sequential order",
		formula: "if y_i * (w^T x_i) <= 0: w := w + y_i * x_i",
		conventions: "Labels y in {-1, +1}",
		outputPrecision: "D integer weights space-separated",
		extraConstraints: ["w_0 = 0, eta = 1", "Update when y * dot(w, x) <= 0", "E sequential epochs"],
	},
	"omni-channel-customer-multinomial-nb": {
		solverMethod: "Multinomial Naive Bayes with Laplace Add-1 Smoothing",
		regularization: "alpha = 1 (Laplace smoothing parameter)",
		formula: "P(w_j | c) = (count(w_j, c) + 1) / (total_tokens_in_c + |V|); score(c) = ln P(c) + sum x_j * ln P(w_j | c)",
		conventions: "Select class with maximum log posterior",
		outputPrecision: "Single integer: predicted class_id",
		extraConstraints: ["Laplace smoothing: alpha = 1", "Log posterior decision rule"],
	},
	"fleet-breakdown-roc-auc": {
		solverMethod: "Receiver Operating Characteristic Area Under Curve (ROC-AUC)",
		formula: "Sort predictions descending, compute True Positive Rate and False Positive Rate across thresholds, integrate via Trapezoidal Rule",
		conventions: "Equivalently Wilcoxon-Mann-Whitney rank statistic",
		outputPrecision: "Single real number, 4 decimal places",
		extraConstraints: ["Trapezoidal rule integration", "Output formatted to 4 decimals"],
	},
	"saturn-rover-support-vector-margin": {
		solverMethod: "Hard-Margin Linear Support Vector Machine (SVM) Margin Calculation",
		formula: "Geometric margin = 2 / ||w||_2; Functional margin = min_i (y_i * (w^T x_i + b))",
		conventions: "Euclidean L2 norm ||w||_2 = sqrt(sum w_j^2)",
		outputPrecision: "Two real numbers: geometric_margin functional_margin (4 decimal places)",
		extraConstraints: ["Geometric margin = 2 / ||w||", "Functional margin = min y*(w^T x + b)"],
	},
	"orion-constellation-kmeans-clustering": {
		solverMethod: "Lloyd's k-Means Clustering (Single Full Update Step)",
		iterations: "Exactly 1 iteration (1 assignment step followed by 1 centroid update step)",
		conventions: "Assign each point to closest centroid under Euclidean distance. Tie-breaking: assign to lower centroid index. Centroid update: mean of assigned points (retain centroid if cluster empty)",
		outputPrecision: "K lines, each with D coordinates formatted to 4 decimal places",
		extraConstraints: ["Exactly 1 full update step (do not iterate to convergence)", "Tie break by lower centroid index"],
	},
	"hyper-cluster-kmeans-inertia": {
		solverMethod: "k-Means Inertia / Within-Cluster Sum of Squares (WCSS)",
		formula: "Inertia = sum_{k=1}^K sum_{x in C_k} ||x - mu_k||^2",
		conventions: "Squared Euclidean distance summed across all points to their assigned cluster centroid",
		outputPrecision: "Single real number, 4 decimal places",
		extraConstraints: ["WCSS = sum ||x - mu||^2", "Output formatted to 4 decimals"],
	},
	"eco-reserve-habitat-kmeans-plus-plus": {
		solverMethod: "k-Means++ Probabilistic Centroid Initialization Distribution",
		formula: "D(x)^2 = min_{c in C} ||x - c||^2; Prob(x) = D(x)^2 / sum_{x'} D(x')^2",
		conventions: "Squared Euclidean distance to nearest existing centroid",
		outputPrecision: "N selection probabilities space-separated, 4 decimal places",
		extraConstraints: ["Prob(x) = D(x)^2 / sum(D(x')^2)", "Squared Euclidean distance"],
	},
	"archaeology-pottery-agglomerative-linkage": {
		solverMethod: "Hierarchical Agglomerative Clustering Linkage Metrics",
		formula: "Single Linkage = min_{u in A, v in B} ||u - v||_2; Complete Linkage = max_{u in A, v in B} ||u - v||_2",
		conventions: "Euclidean distance metric between all pairwise cross-cluster elements",
		outputPrecision: "Two real numbers: single_linkage complete_linkage (4 decimal places)",
		extraConstraints: ["Single linkage: min pairwise distance", "Complete linkage: max pairwise distance"],
	},
	"urban-transit-density-dbscan": {
		solverMethod: "DBSCAN Density-Based Spatial Clustering Point Classification",
		conventions: "Parameters eps and minPts read from input line 1. CORE: |N_eps(p)| >= minPts (including p itself). BORDER: non-core point within eps of at least one CORE point. NOISE: neither CORE nor BORDER. Distance: Euclidean distance",
		outputPrecision: "N lines, each containing CORE, BORDER, or NOISE",
		extraConstraints: ["CORE if >= minPts neighbors within eps (including itself)", "BORDER if within eps of a CORE point, else NOISE"],
	},
	"spectral-sound-gmm-expectation-maximization": {
		solverMethod: "1D Gaussian Mixture Model Expectation (E-Step) Responsibilities",
		formula: "gamma_{ik} = (pi_k * N(x_i | mu_k, sigma^2_k)) / sum_{j=1}^K (pi_j * N(x_i | mu_j, sigma^2_j))",
		conventions: "Gaussian PDF: N(x | mu, sigma^2) = (1 / sqrt(2*pi*sigma^2)) * exp(-(x - mu)^2 / (2*sigma^2))",
		outputPrecision: "N lines, each with K responsibility values space-separated, 4 decimal places",
		extraConstraints: ["E-step responsibility formula", "1D Gaussian PDF normalization"],
	},
	"galaxy-cluster-silhouette-score": {
		solverMethod: "Silhouette Coefficient Cluster Quality Metric",
		formula: "s(i) = (b(i) - a(i)) / max(a(i), b(i)); if cluster size is 1: s(i) = 0.0000; return mean s(i)",
		conventions: "a(i) is mean intra-cluster distance; b(i) is mean distance to points in nearest neighboring cluster. Euclidean metric",
		outputPrecision: "Single real number: mean silhouette score, 4 decimal places",
		extraConstraints: ["s(i) = (b(i) - a(i)) / max(a, b)", "s(i) = 0 for single-point clusters"],
	},
	"retail-customer-rfm-segmentation": {
		solverMethod: "RFM (Recency, Frequency, Monetary) Composite Score Normalization",
		formula: "Min-Max normalize each feature: x' = (x - x_min) / (x_max - x_min) (if x_max == x_min, x' = 1.0). Invert Recency: R_score = 1 - R'. Score = 0.2*R_score + 0.3*F' + 0.5*M'",
		conventions: "Lower recency days gives higher score",
		outputPrecision: "N scores space-separated, 4 decimal places",
		extraConstraints: ["Min-max normalization across features", "Score = 0.2*(1 - R') + 0.3*F' + 0.5*M'"],
	},
	"seismic-sensor-medoid-clustering": {
		solverMethod: "Partitioning Around Medoids (PAM) Total Clustering Cost",
		formula: "Cost = sum_{i=1}^N min_{m in Medoids} ||x_i - m||_1 (Manhattan L1 distance)",
		conventions: "L1 Manhattan distance: sum_d |x_d - m_d|",
		outputPrecision: "Single real number, 4 decimal places",
		extraConstraints: ["Manhattan distance ||x - m||_1", "Sum of distances to closest medoid"],
	},
	"anomalous-substation-distance-outliers": {
		solverMethod: "k-NN Distance Anomaly Detection",
		conventions: "For each point, compute Euclidean distance to its k-th nearest DISTINCT neighbor among the other N-1 points (excluding the point itself). If dist > threshold: OUTLIER, else: NORMAL",
		outputPrecision: "N lines: dist STATUS (dist formatted to 4 decimal places)",
		extraConstraints: ["k-th nearest neighbor among the other N-1 distinct points", "Flag OUTLIER if dist > threshold, else NORMAL"],
	},
	"helios-reactor-batch-gradient-descent": {
		solverMethod: "Batch Gradient Descent on Quadratic Cost Function",
		initialParams: "w_0 read from input line 4 (vector of length D)",
		learningRate: "alpha read from input line 1",
		iterations: "K iterations (exact)",
		formula: "grad = A * w - b (A is diagonal matrix), w := w - alpha * grad",
		conventions: "Diagonal matrix A given as D positive diagonal entries",
		outputPrecision: "D weights space-separated, 4 decimal places",
		extraConstraints: ["grad = A * w - b", "w := w - alpha * grad for K steps"],
	},
	"kinetic-missile-momentum-optimizer": {
		solverMethod: "Classical Momentum Optimization Update",
		initialParams: "w_0 from line 2, v_0 from line 3",
		learningRate: "alpha from line 1",
		iterations: "Process K incoming gradient vectors",
		regularization: "beta (momentum decay) from line 1",
		formula: "v := beta * v + alpha * g, w := w - v",
		conventions: "Velocity update precedes parameter update",
		outputPrecision: "Line 1: final_w, Line 2: final_v (all 4 decimal places)",
		extraConstraints: ["v := beta * v + alpha * g", "w := w - v"],
	},
	"crypto-volatility-adagrad-optimizer": {
		solverMethod: "AdaGrad Adaptive Gradient Optimizer",
		initialParams: "w_0 from input line 2, G_0 = [0, 0, ..., 0]",
		learningRate: "alpha from line 1",
		iterations: "Process K incoming gradient vectors",
		tolerance: "eps = 1e-8 (numerical stability denominator)",
		formula: "G := G + g^2, w := w - (alpha / (sqrt(G) + eps)) * g",
		conventions: "Coordinate-wise accumulated sum of squared gradients",
		outputPrecision: "Line 1: final_w, Line 2: final_G (all 4 decimal places)",
		extraConstraints: ["G := G + g^2", "w := w - (alpha / (sqrt(G) + 1e-8)) * g"],
	},
	"pulsar-radio-rmsprop-update": {
		solverMethod: "RMSprop Exponential Moving Average Optimizer",
		initialParams: "w_0 from input line 2, v_0 = [0, 0, ..., 0]",
		learningRate: "alpha from line 1",
		iterations: "Process K incoming gradient vectors",
		regularization: "beta from line 1",
		tolerance: "eps = 1e-8",
		formula: "v := beta * v + (1 - beta) * g^2, w := w - (alpha / (sqrt(v) + eps)) * g",
		conventions: "Moving average of squared gradients",
		outputPrecision: "Line 1: final_w, Line 2: final_v (all 4 decimal places)",
		extraConstraints: ["v := beta * v + (1 - beta) * g^2", "w := w - (alpha / (sqrt(v) + 1e-8)) * g"],
	},
	"neural-forge-adam-optimizer": {
		solverMethod: "Adam (Adaptive Moment Estimation) Optimizer",
		initialParams: "w_0 from input line 2, m_0 = [0, 0, ..., 0], v_0 = [0, 0, ..., 0]",
		learningRate: "alpha from line 1",
		iterations: "K timesteps (t = 1 to K)",
		regularization: "beta1 and beta2 from line 1",
		tolerance: "eps = 1e-8",
		formula: "m_t = beta1*m_{t-1} + (1-beta1)*g, v_t = beta2*v_{t-1} + (1-beta2)*g^2, m_hat = m_t / (1 - beta1^t), v_hat = v_t / (1 - beta2^t), w_t = w_{t-1} - (alpha * m_hat) / (sqrt(v_hat) + eps)",
		conventions: "Timestep t is 1-indexed (t = 1..K) for moment bias corrections",
		outputPrecision: "D weights space-separated, 4 decimal places",
		extraConstraints: ["Bias-corrected moments m_hat, v_hat", "eps = 1e-8, t starts at 1"],
	},
	"supercollider-learning-rate-decay": {
		solverMethod: "Learning Rate Decay Schedules Comparison",
		learningRate: "alpha_0 read from input line 1",
		formula: "Step decay: alpha_0 * gamma^(floor(t / s)); Exponential decay: alpha_0 * exp(-k * t); Inverse-time decay: alpha_0 / (1 + k * t)",
		conventions: "Evaluate at specified timestep t",
		outputPrecision: "Three real numbers: step_alpha exp_alpha inv_alpha (4 decimal places)",
		extraConstraints: ["Step decay: alpha_0 * gamma^(floor(t/s))", "Exponential decay: alpha_0 * exp(-k*t)", "Inverse-time: alpha_0 / (1 + k*t)"],
	},
	"deep-mine-backtracking-line-search": {
		solverMethod: "Backtracking Armijo Line Search Condition",
		tolerance: "Armijo c = 0.1, contraction factor rho = 0.5, alpha_init = 1.0",
		formula: "Armijo condition: f(x - alpha * grad) <= f(x) - c * alpha * ||grad||^2",
		conventions: "Max line search contractions = 10",
		outputPrecision: "Two real numbers: accepted_alpha f_new (4 decimal places)",
		extraConstraints: ["c = 0.1, rho = 0.5, alpha_init = 1.0", "Armijo condition check"],
	},
	"orbital-docking-l-bfgs-two-loop": {
		solverMethod: "BFGS Quasi-Newton Curvature Condition & Secant Equation",
		formula: "s_k = x_{k+1} - x_k, y_k = g_{k+1} - g_k; Curvature: s_k^T y_k > 0",
		conventions: "Evaluates whether curvature condition holds for positive definite Hessian approximation",
		outputPrecision: "Line 1: dot_product (4 decimal places), Line 2: CURVATURE_SATISFIED or CURVATURE_VIOLATED",
		extraConstraints: ["Curvature: s^T y > 0", "dot_product and status string"],
	},
	"quantum-annealer-gradient-clipping": {
		solverMethod: "Global Gradient Norm Clipping",
		regularization: "Max norm threshold C read from input line 1",
		formula: "norm = sqrt(sum g_d^2); if norm > C: g := g * (C / norm)",
		conventions: "If norm <= C, gradients remain unchanged",
		outputPrecision: "D clipped gradients space-separated, 4 decimal places",
		extraConstraints: ["If ||g|| > C: g := g * (C / ||g||)", "Threshold C from input"],
	},
	"nano-device-subgradient-descent": {
		solverMethod: "Subgradient Descent on L1 Regularized Objective",
		learningRate: "alpha read from input line 1",
		formula: "subgrad(w_j) = sign(w_j) (where sign(0) = 0); w := w - alpha * subgrad",
		conventions: "Non-differentiable point 0 has subgradient 0",
		outputPrecision: "D updated weights space-separated, 4 decimal places",
		extraConstraints: ["sign(0) = 0", "w := w - alpha * sign(w)"],
	},
	"spectral-telescope-pca-projection": {
		solverMethod: "Principal Component Analysis (PCA) 1D Projection",
		formula: "Center: x_c = x - mean(x); Project: z = dot(x_c, v) where v is given unit eigenvector",
		conventions: "Feature-wise mean subtraction before dot product projection",
		outputPrecision: "N projected scalar values space-separated, 4 decimal places",
		extraConstraints: ["Subtract mean before projection", "z = dot(x - mean, v)"],
	},
	"genomic-variance-explained-ratio": {
		solverMethod: "PCA Explained Variance Ratio & Cumulative Variance",
		formula: "EVR_i = lambda_i / sum(lambda); Cumulative_k = sum_{i=1}^k EVR_i",
		conventions: "Eigenvalues sorted descending",
		outputPrecision: "Line 1: EVR values, Line 2: Cumulative EVR values (all 4 decimal places)",
		extraConstraints: ["EVR = lambda_i / sum(lambda)", "Cumulative sums formatted to 4 decimals"],
	},
	"deep-vault-svd-low-rank-reconstruction": {
		solverMethod: "Truncated Singular Value Decomposition (SVD) Low-Rank Reconstruction",
		formula: "A_K = sum_{k=1}^K sigma_k * u_k * v_k^T",
		conventions: "Outer product sum over top K singular triplets",
		outputPrecision: "Rows of reconstructed matrix, 4 decimal places",
		extraConstraints: ["A_K = sum_{k=1}^K sigma_k * u_k * v_k^T", "Rank K from input line 1"],
	},
	"tactical-radar-gram-schmidt-orthogonalization": {
		solverMethod: "Gram-Schmidt Orthonormalization Process",
		formula: "u_k = v_k - sum_{j=1}^{k-1} (dot(v_k, e_j)) * e_j; e_k = u_k / ||u_k||_2",
		conventions: "Sequential projection onto orthogonal complement and normalization",
		outputPrecision: "K orthonormal vectors, each with D coordinates formatted to 4 decimal places",
		extraConstraints: ["Gram-Schmidt orthogonalization", "Normalize each vector to unit norm ||e_k|| = 1"],
	},
	"macro-economy-correlation-to-covariance": {
		solverMethod: "Correlation Matrix to Covariance Matrix Conversion",
		formula: "Sigma_{ij} = Corr_{ij} * std_i * std_j",
		conventions: "Uses given standard deviation vector std",
		outputPrecision: "D x D covariance matrix, each value 4 decimal places",
		extraConstraints: ["Sigma_{ij} = Corr_{ij} * std_i * std_j", "Output formatted to 4 decimals"],
	},
	"hyperspectral-satellite-lda-scatter": {
		solverMethod: "Linear Discriminant Analysis (LDA) Between-Class Scatter Matrix",
		formula: "S_B = sum_{c=1}^C N_c * (mu_c - mu_overall) * (mu_c - mu_overall)^T",
		conventions: "Outer product of class mean deviations weighted by class count N_c",
		outputPrecision: "D x D scatter matrix, 4 decimal places",
		extraConstraints: ["S_B = sum N_c * (mu_c - mu) * (mu_c - mu)^T", "Output formatted to 4 decimals"],
	},
	"drone-swarm-mahalanobis-distance": {
		solverMethod: "Mahalanobis Distance with Known Covariance Matrix",
		formula: "D_M(x, mu) = sqrt((x - mu)^T * Sigma^(-1) * (x - mu))",
		conventions: "Accounts for feature correlations via inverse covariance matrix",
		outputPrecision: "Single real number, 4 decimal places",
		extraConstraints: ["D_M = sqrt((x - mu)^T * Sigma^(-1) * (x - mu))", "Output formatted to 4 decimals"],
	},
	"holographic-memory-cosine-similarity-matrix": {
		solverMethod: "Pairwise Cosine Similarity Matrix",
		formula: "CosSim(u, v) = dot(u, v) / (||u||_2 * ||v||_2)",
		conventions: "If either vector has norm 0, define similarity as 0.0000",
		outputPrecision: "N x N similarity matrix, 4 decimal places",
		extraConstraints: ["Cosine similarity: dot(u, v) / (||u|| * ||v||)", "Zero norm vectors yield 0.0000"],
	},
	"clinical-trial-standard-scaler": {
		solverMethod: "StandardScaler (Z-Score Normalization)",
		conventions: "Population standard deviation: sigma_d = sqrt((1/N) * sum((x_d - mu_d)^2)) (divide by N). If sigma_d == 0, output 0.0000 for that coordinate. z = (x - mu) / sigma",
		outputPrecision: "N lines, each with D standardized features (4 decimal places)",
		extraConstraints: ["Population standard deviation (divide by N)", "If std == 0, set z = 0.0000"],
	},
	"sensor-grid-min-max-normalization": {
		solverMethod: "Min-Max Feature Scaling to [0, 1] Range",
		formula: "x' = (x - min) / (max - min)",
		conventions: "If max == min, map all values to 0.0000",
		outputPrecision: "N lines, each with D scaled features (4 decimal places)",
		extraConstraints: ["x' = (x - min) / (max - min)", "If max == min, output 0.0000"],
	},
	"smart-city-one-hot-encoder": {
		solverMethod: "One-Hot Feature Encoding for Categorical Data",
		conventions: "Alphabetically sort all distinct categories from input to determine column order. For each sample, output 1 for its active category and 0 elsewhere",
		outputPrecision: "N lines, each containing binary integers 0 or 1",
		extraConstraints: ["Alphabetical category ordering", "Binary one-hot vectors"],
	},
	"hydrology-missing-data-imputation": {
		solverMethod: "Missing Data Imputation (Mean & Median Strategies)",
		conventions: "Missing values are represented as -999.0 or NaN. Compute mean of valid observed entries for each column and replace missing entries",
		outputPrecision: "N lines, each with D imputed values (4 decimal places)",
		extraConstraints: ["Impute missing entries (-999.0) with column mean of valid values", "4 decimal places"],
	},
	"automotive-polynomial-feature-expansion": {
		solverMethod: "2-Feature Quadratic Polynomial Expansion",
		formula: "phi(x1, x2) = [1, x1, x2, x1^2, x1*x2, x2^2]",
		conventions: "Fixed degree 2 ordering with bias column prepended",
		outputPrecision: "N lines, each containing 6 expanded feature values (4 decimal places)",
		extraConstraints: ["Expansion order: 1, x1, x2, x1^2, x1*x2, x2^2", "Output 6 columns formatted to 4 decimals"],
	},
	"text-stream-target-encoding": {
		solverMethod: "Target Encoding with Empirical Bayes m-Estimate Smoothing",
		formula: "encoded_c = (n_c * mean_y_c + m * global_mean_y) / (n_c + m)",
		conventions: "Smoothing parameter m read from input line 1",
		outputPrecision: "Encoded target values, 4 decimal places",
		extraConstraints: ["Smoothing formula: (n_c * y_c + m * y_global) / (n_c + m)", "Smoothing m from input"],
	},
	"avionics-quantile-binning-transformer": {
		solverMethod: "Equal-Frequency Quantile Binning Discretization",
		conventions: "Sort data to find empirical bin edges for K equal-frequency quantiles. Assign 0-indexed bin integer",
		outputPrecision: "N integer bin assignments space-separated",
		extraConstraints: ["K equal-frequency bins", "0-indexed bin integer"],
	},
	"credit-risk-weight-of-evidence-iv": {
		solverMethod: "Weight of Evidence (WoE) and Information Value (IV)",
		formula: "WoE_i = ln((Goods_i / Total_Goods) / (Bads_i / Total_Bads)), IV = sum ((Goods_i/Total_Goods) - (Bads_i/Total_Bads)) * WoE_i",
		conventions: "Use natural logarithm ln. Numerical safeguard: if count is 0, add 0.5",
		outputPrecision: "Line 1: WoE values for each bin, Line 2: total IV (4 decimal places)",
		extraConstraints: ["Natural log ln for WoE", "Total Information Value IV"],
	},
	"perceptron-activation-functions-zoo": {
		solverMethod: "Neural Network Activation Functions Evaluation",
		formula: "ReLU: max(0, x); LeakyReLU: max(0.01*x, x); Sigmoid: 1/(1 + exp(-x)); Tanh: tanh(x)",
		conventions: "Fixed LeakyReLU slope alpha = 0.01",
		outputPrecision: "For each input x: ReLU LeakyReLU Sigmoid Tanh (4 decimal places)",
		extraConstraints: ["LeakyReLU alpha = 0.01", "Output: ReLU LeakyReLU Sigmoid Tanh"],
	},
	"deep-cortex-multilayer-forward-pass": {
		solverMethod: "Two-Layer Feedforward Neural Network Forward Pass",
		formula: "Hidden: h = ReLU(W1 * x + b1); Output: y_hat = Sigmoid(W2 * h + b2)",
		conventions: "ReLU(z) = max(0, z), Sigmoid(z) = 1 / (1 + exp(-z))",
		outputPrecision: "Predicted output probabilities, 4 decimal places",
		extraConstraints: ["Hidden activation: ReLU", "Output activation: Sigmoid", "Forward pass: y = Sigmoid(W2 * ReLU(W1*x + b1) + b2)"],
	},
	"neural-foundry-cross-entropy-loss": {
		solverMethod: "Multi-Class Categorical Cross-Entropy Loss",
		tolerance: "eps = 1e-15 clamped to probabilities: max(eps, min(1 - eps, p))",
		formula: "Loss = -(1/N) * sum_{i=1}^N sum_{c=1}^C y_{i,c} * ln(p_{i,c})",
		conventions: "One-hot ground truth labels y, predicted softmax probabilities p",
		outputPrecision: "Single real number: mean cross-entropy loss, 4 decimal places",
		extraConstraints: ["Natural log ln", "Clamp probabilities with eps = 1e-15 to avoid log(0)"],
	},
	"backprop-gradient-computation-single-layer": {
		solverMethod: "Single Dense Layer Backpropagation Gradients",
		formula: "dL/dW = delta * x^T (outer product), dL/db = delta",
		conventions: "Given upstream error gradient delta and layer input x",
		outputPrecision: "Flattened weight gradients followed by bias gradients (4 decimal places)",
		extraConstraints: ["dL/dW = delta * x^T", "dL/db = delta"],
	},
	"dropout-regularization-mask-generator": {
		solverMethod: "Inverted Dropout Forward Step",
		formula: "scaling = 1 / (1 - p); for each activation: if mask == 1: a * scaling; else: 0.0000",
		conventions: "Drop probability p read from input line 1. Inverted dropout preserves expected activation sum during training",
		outputPrecision: "N lines of scaled activations, 4 decimal places",
		extraConstraints: ["Inverted dropout scaling: 1 / (1 - p)", "Drop probability p from input"],
	},
	"batch-normalization-forward-step": {
		solverMethod: "Batch Normalization (BatchNorm) Forward Pass",
		tolerance: "eps = 1e-5 (variance stability constant)",
		formula: "mu = (1/N)*sum(x), var = (1/N)*sum((x - mu)^2), x_hat = (x - mu) / sqrt(var + eps), y = gamma * x_hat + beta",
		conventions: "Use population variance: divide by N (not N-1)",
		outputPrecision: "N lines, each with D normalized and scaled values (4 decimal places)",
		extraConstraints: ["eps = 1e-5", "Population variance: divide by N", "y = gamma * x_hat + beta"],
	},
	"layer-normalization-transformer-step": {
		solverMethod: "Layer Normalization (LayerNorm) Forward Pass",
		tolerance: "eps = 1e-5",
		formula: "Compute mean and variance across feature dimension D for each sample: mu_i = (1/D)*sum_d x_{i,d}, var_i = (1/D)*sum_d (x_{i,d} - mu_i)^2; y_i = gamma * ((x_i - mu_i) / sqrt(var_i + eps)) + beta",
		conventions: "Normalizes across features independently for each individual token/sample",
		outputPrecision: "N lines, each with D LayerNorm outputs (4 decimal places)",
		extraConstraints: ["Normalize across feature dimension D", "eps = 1e-5", "y = gamma * x_hat + beta"],
	},
	"convolution-1d-feature-extractor": {
		solverMethod: "1D Valid Discrete Convolution",
		formula: "(x * w)[i] = sum_{j=0}^{K-1} x[i + j] * w[j]",
		conventions: "Valid padding: output length is L - K + 1",
		outputPrecision: "Output feature map values space-separated, 4 decimal places",
		extraConstraints: ["Valid convolution (no padding)", "Output length: L - K + 1"],
	},
	"vision-core-2d-max-pooling": {
		solverMethod: "2D Spatial Max-Pooling with Non-Overlapping Stride",
		conventions: "Window size P x P with stride P x P. In each pooling window, take maximum value",
		outputPrecision: "Pooled 2D matrix rows, 4 decimal places",
		extraConstraints: ["Non-overlapping stride equal to window size P", "Max operation over P x P window"],
	},
	"self-attention-scaled-dot-product": {
		solverMethod: "Scaled Dot-Product Self-Attention",
		formula: "Attention(Q, K, V) = Softmax((Q * K^T) / sqrt(d_k)) * V",
		conventions: "Softmax applied row-wise along key dimension. Scale by sqrt(d_k)",
		outputPrecision: "Attention output matrix rows, 4 decimal places",
		extraConstraints: ["Scale by sqrt(d_k)", "Row-wise Softmax", "Attention = Softmax(Q K^T / sqrt(d_k)) * V"],
	},
	"alexandria-term-frequency-tf-idf": {
		solverMethod: "TF-IDF (Term Frequency - Inverse Document Frequency) Computation",
		formula: "TF(t, d) = count(t, d) / |d|; IDF(t) = ln((1 + N) / (1 + DF(t))) + 1; TF-IDF = TF * IDF",
		conventions: "Smooth IDF formula using natural log ln",
		outputPrecision: "TF-IDF matrix values, 4 decimal places",
		extraConstraints: ["Smooth IDF: ln((1 + N) / (1 + DF)) + 1", "TF = count / total_tokens"],
	},
	"corpus-bag-of-words-vectorizer": {
		solverMethod: "Bag-of-Words (BoW) Term Frequency Vectorizer",
		conventions: "Build vocabulary of unique tokens sorted alphabetically. Count term frequencies for each document",
		outputPrecision: "Lines of integer token count vectors",
		extraConstraints: ["Alphabetical vocabulary ordering", "Integer frequency counts"],
	},
	"lexicon-ngram-frequency-analyzer": {
		solverMethod: "Character N-Gram Frequency Counter",
		conventions: "N read from input line 1. Extract all overlapping contiguous substrings of length N. Output unique n-grams sorted alphabetically with frequency",
		outputPrecision: "Lines: ngram count",
		extraConstraints: ["Contiguous n-grams of length N", "Sort output alphabetically by n-gram string"],
	},
	"machine-translation-bleu-score": {
		solverMethod: "Bilingual Evaluation Understudy (BLEU-1 & BLEU-2) Metric",
		formula: "Clipped n-gram precision p_n; BP = exp(min(0, 1 - r/c)); BLEU = BP * exp(0.5 * ln(p1) + 0.5 * ln(p2))",
		conventions: "r is reference length, c is candidate length. Clip precision by max count in reference",
		outputPrecision: "Single real number: BLEU score, 4 decimal places",
		extraConstraints: ["Brevity penalty: BP = exp(min(0, 1 - r/c))", "Geometric mean of p1 and p2"],
	},
	"byte-pair-encoding-merge-step": {
		solverMethod: "Byte-Pair Encoding (BPE) Single Token Merge Step",
		conventions: "Count all adjacent symbol pairs across vocabulary weighted by word frequency. Find most frequent pair (break ties alphabetically). Replace with merged symbol",
		outputPrecision: "Merged vocabulary lines and the chosen merged pair",
		extraConstraints: ["Find highest frequency adjacent pair", "Break ties alphabetically"],
	},
	"semantic-search-bm25-ranking": {
		solverMethod: "Okapi BM25 Document Ranking Algorithm",
		regularization: "k1 = 1.2, b = 0.75 (standard parameters)",
		formula: "IDF(q) = ln((N - n_q + 0.5) / (n_q + 0.5) + 1); BM25 = sum_q IDF(q) * (f(q, d) * (k1 + 1)) / (f(q, d) + k1 * (1 - b + b * (|d| / avgdl)))",
		conventions: "Standard BM25 document score with Robertson-Spärck Jones IDF",
		outputPrecision: "Document scores sorted or in order, 4 decimal places",
		extraConstraints: ["k1 = 1.2, b = 0.75", "Okapi BM25 scoring formula"],
	},
	"word-embedding-cosine-analogy": {
		solverMethod: "Word Vector Arithmetic Analogy Solver",
		formula: "target = v_b - v_a + v_c; find word w in vocabulary maximizing CosSim(target, v_w) where w not in {a, b, c}",
		conventions: "Exclude input query words a, b, c from candidate pool",
		outputPrecision: "Word string with maximum cosine similarity",
		extraConstraints: ["Target vector: v_b - v_a + v_c", "Exclude query words from candidates"],
	},
	"spam-filter-naive-bayes-log-odds": {
		solverMethod: "Naive Bayes Log-Odds Classification",
		formula: "LogOdds = ln(P(Spam) / P(Ham)) + sum_w ln(P(w|Spam) / P(w|Ham)); Classify SPAM if LogOdds > 0 else HAM",
		conventions: "Log-likelihood ratio decision rule",
		outputPrecision: "Line 1: log_odds (4 decimal places), Line 2: SPAM or HAM",
		extraConstraints: ["Log-odds: ln(P(Spam)/P(Ham)) + sum ln(P(w|Spam)/P(w|Ham))", "Classify SPAM if > 0 else HAM"],
	},
	"cinephile-user-collaborative-filtering": {
		solverMethod: "User-Based Collaborative Filtering with Pearson Correlation",
		formula: "sim(u, v) = PearsonCorrelation(ratings_u, ratings_v) over co-rated items; predicted rating = mean_u + sum(sim*(r_vi - mean_v)) / sum(|sim|)",
		conventions: "Exclude users with non-positive correlation",
		outputPrecision: "Predicted ratings formatted to 4 decimal places",
		extraConstraints: ["Pearson correlation similarity", "Centered mean rating prediction"],
	},
	"e-commerce-item-cosine-recommender": {
		solverMethod: "Item-Based Collaborative Filtering with Adjusted Cosine Similarity",
		formula: "sim(i, j) = dot(r_i - mean_u, r_j - mean_u) / (||r_i - mean_u|| * ||r_j - mean_u||)",
		conventions: "Adjusted for user mean ratings",
		outputPrecision: "Top item recommendation or similarity scores, 4 decimal places",
		extraConstraints: ["Adjusted cosine similarity", "Output formatted to 4 decimals"],
	},
	"streaming-matrix-factorization-sgd": {
		solverMethod: "Matrix Factorization Online SGD Step (Latent Factor Model)",
		learningRate: "gamma read from input line 1",
		regularization: "lambda read from input line 1",
		formula: "error = r_{ui} - dot(p_u, q_i); p_u := p_u + gamma * (error * q_i - lambda * p_u); q_i := q_i + gamma * (error * p_u - lambda * q_i)",
		conventions: "Simultaneous gradient update of user latent vector p_u and item latent vector q_i",
		outputPrecision: "Line 1: updated p_u, Line 2: updated q_i (all 4 decimal places)",
		extraConstraints: ["error = r - dot(p_u, q_i)", "p_u := p_u + gamma*(error*q_i - lambda*p_u)", "q_i := q_i + gamma*(error*p_u - lambda*q_i)"],
	},
	"music-box-jaccard-playlist-similarity": {
		solverMethod: "Jaccard Similarity Coefficient for Binary Item Sets",
		formula: "J(A, B) = |A intersection B| / |A union B|",
		conventions: "If union is empty, similarity is 1.0000",
		outputPrecision: "Single real number, 4 decimal places",
		extraConstraints: ["Jaccard index: |A inter B| / |A union B|", "Output formatted to 4 decimals"],
	},
	"app-store-ndcg-ranking-metric": {
		solverMethod: "Normalized Discounted Cumulative Gain (NDCG@K)",
		formula: "DCG@K = sum_{i=1}^K (2^r_i - 1) / log2(i + 1); NDCG@K = DCG@K / IDCG@K",
		conventions: "IDCG is DCG of ground truth ratings sorted descending. Base-2 logarithm",
		outputPrecision: "Single real number, 4 decimal places",
		extraConstraints: ["DCG = sum (2^r - 1) / log2(i + 1)", "NDCG = DCG / IDCG"],
	},
	"social-graph-mean-reciprocal-rank": {
		solverMethod: "Mean Reciprocal Rank (MRR) Information Retrieval Metric",
		formula: "MRR = (1 / |Q|) * sum_{q=1}^{|Q|} (1 / rank_q)",
		conventions: "rank_q is 1-indexed position of first relevant item. If not found in ranked list, 1/rank = 0",
		outputPrecision: "Single real number, 4 decimal places",
		extraConstraints: ["MRR = (1 / |Q|) * sum (1 / rank)", "1-indexed rank position"],
	},
	"video-feed-hit-ratio-at-k": {
		solverMethod: "Hit Ratio at K (HR@K) Evaluation Metric",
		formula: "Hit@K = 1 if ground_truth_item in top_K_recommended else 0; return mean Hit across all test users",
		conventions: "Binary hit score averaged across user queries",
		outputPrecision: "Single real number, 4 decimal places",
		extraConstraints: ["Hit Ratio: proportion of queries where target is in top K", "Output formatted to 4 decimals"],
	},
	"bazaar-als-single-factor-update": {
		solverMethod: "Alternating Least Squares (ALS) Closed-Form Ridge Factor Update",
		regularization: "lambda read from input line 1",
		formula: "p_u = (sum_{i in R(u)} q_i * q_i^T + lambda * I)^(-1) * sum_{i in R(u)} r_{ui} * q_i",
		conventions: "Exact ridge regression closed form for user latent vector given fixed item factors",
		outputPrecision: "D factor weights space-separated, 4 decimal places",
		extraConstraints: ["ALS ridge update: (Q^T Q + lambda*I)^(-1) Q^T r", "lambda from input"],
	},
	"meteorology-simple-moving-average": {
		solverMethod: "Simple Moving Average (SMA) Time Series Smoothing",
		conventions: "Window size W read from input line 1. SMA_t = (1/W) * sum_{i=0}^{W-1} x_{t-i}. Valid output begins at index W - 1",
		outputPrecision: "N - W + 1 smoothed values space-separated, 4 decimal places",
		extraConstraints: ["Window size W", "SMA = (1/W) * sum_{i=0}^{W-1} x_{t-i}"],
	},
	"grid-load-holt-winters-trend": {
		solverMethod: "Holt's Linear Exponential Smoothing (Level and Trend)",
		learningRate: "alpha (level smoothing) and beta (trend smoothing) from line 1",
		initialParams: "L_0 = y_0, T_0 = y_1 - y_0",
		formula: "L_t = alpha * y_t + (1 - alpha) * (L_{t-1} + T_{t-1}); T_t = beta * (L_t - L_{t-1}) + (1 - beta) * T_{t-1}; Forecast_{t+h} = L_t + h * T_t",
		conventions: "Recursive equations starting at t = 1",
		outputPrecision: "Final level L_N and trend T_N (4 decimal places)",
		extraConstraints: ["Level: L_t = alpha*y_t + (1-alpha)*(L_{t-1} + T_{t-1})", "Trend: T_t = beta*(L_t - L_{t-1}) + (1-beta)*T_{t-1}"],
	},
	"stock-exchange-autoregressive-ar1": {
		solverMethod: "Autoregressive Order 1 AR(1) Model Estimation & Forecast",
		formula: "phi = sum((y_t - mean)*(y_{t-1} - mean)) / sum((y_{t-1} - mean)^2), c = mean * (1 - phi); Forecast y_{T+1} = c + phi * y_T",
		conventions: "Mean computed over time series",
		outputPrecision: "phi c forecast space-separated, 4 decimal places",
		extraConstraints: ["AR(1) parameter formulas", "y_{T+1} = c + phi * y_T"],
	},
	"river-discharge-lagged-features": {
		solverMethod: "Time Series Lagged Feature Matrix Construction",
		conventions: "Lag order p read from input line 1. For each timestep t from p to N-1, create feature vector [y_{t-1}, y_{t-2}, ..., y_{t-p}] and target y_t",
		outputPrecision: "N - p rows of lagged feature matrix, 4 decimal places",
		extraConstraints: ["Lag order p", "Row format: y_{t-1} ... y_{t-p} y_t"],
	},
	"telecom-traffic-rolling-z-score": {
		solverMethod: "Rolling Z-Score Anomaly Detection",
		conventions: "Window size W read from input line 1. Over sliding window of size W, compute mean mu and population std dev sigma = sqrt((1/W)*sum((x - mu)^2)). Z = (x_t - mu) / sigma",
		outputPrecision: "Rolling Z-scores formatted to 4 decimal places",
		extraConstraints: ["Window size W", "Population std dev over window", "Z = (x - mu) / sigma"],
	},
	"seismic-station-autocorrelation-function": {
		solverMethod: "Sample Autocorrelation Function (ACF)",
		formula: "r_k = sum_{t=k+1}^N (y_t - mean(y))*(y_{t-k} - mean(y)) / sum_{t=1}^N (y_t - mean(y))^2",
		conventions: "Lag k from input. Normalizes by total sample variance",
		outputPrecision: "Single real number: r_k, 4 decimal places",
		extraConstraints: ["Sample ACF formula", "Output formatted to 4 decimals"],
	},
	"adaboost-sample-weight-update": {
		solverMethod: "AdaBoost Weak Classifier Weight & Sample Weight Update",
		formula: "Classifier weight: alpha_t = 0.5 * ln((1 - eps_t) / eps_t); Update: w_{i, t+1} = (w_{i, t} * exp(-alpha_t * y_i * h_t(x_i))) / Z_t",
		conventions: "Z_t is normalization factor ensuring sum(w_{t+1}) = 1.0. Labels y, h in {-1, +1}",
		outputPrecision: "Line 1: alpha_t (4 decimals), Line 2: updated weights w space-separated (4 decimals)",
		extraConstraints: ["alpha = 0.5 * ln((1 - eps) / eps)", "Normalize updated weights to sum to 1"],
	},
	"random-forest-majority-ensemble": {
		solverMethod: "Random Forest Majority Voting Ensemble Aggregator",
		conventions: "For each test instance, aggregate predictions across all M trees. Assign class with strict majority vote. Tie-breaking: select lower class index",
		outputPrecision: "N predicted integer class labels space-separated",
		extraConstraints: ["Majority voting", "Tie break by lower class index"],
	},
	"gradient-boosting-residual-targets": {
		solverMethod: "Gradient Boosting Pseudo-Residuals for Squared Error Loss",
		formula: "residual r_i = y_i - F_{m-1}(x_i) = - dL/dF",
		conventions: "Negative gradient of MSE loss 0.5 * (y - F)^2",
		outputPrecision: "N pseudo-residuals space-separated, 4 decimal places",
		extraConstraints: ["r_i = y_i - F(x_i)", "Output formatted to 4 decimals"],
	},
	"xgboost-optimal-leaf-weight": {
		solverMethod: "XGBoost Optimal Leaf Weight & Split Gain",
		regularization: "lambda (L2 leaf penalty) and gamma (tree complexity penalty) from line 1",
		formula: "w* = -G / (H + lambda), Gain = 0.5 * [ G_L^2 / (H_L + lambda) + G_R^2 / (H_R + lambda) - (G_L + G_R)^2 / (H_L + H_R + lambda) ] - gamma",
		conventions: "G is sum of 1st gradients, H is sum of 2nd Hessians",
		outputPrecision: "Line 1: optimal_w, Line 2: split_gain (all 4 decimal places)",
		extraConstraints: ["w* = -G / (H + lambda)", "Gain formula with L2 penalty lambda and tree penalty gamma"],
	},
	"bagging-bootstrap-sample-generator": {
		solverMethod: "Bootstrap Aggregation (Bagging) Resampling with Replacement",
		conventions: "Given bootstrap sample indices, assemble the resampled dataset. Compute out-of-bag (OOB) indices not selected in bootstrap",
		outputPrecision: "Line 1: Resampled records, Line 2: OOB indices sorted ascending",
		extraConstraints: ["Bootstrap sampling with replacement", "OOB indices sorted ascending"],
	},
	"stacking-ensemble-meta-feature-matrix": {
		solverMethod: "Stacking Classifier Meta-Feature Matrix Assembly",
		conventions: "Concatenate K base-model cross-validated probability predictions horizontally to form meta-training matrix for blender model",
		outputPrecision: "N rows of meta-features, 4 decimal places",
		extraConstraints: ["Concatenate predictions horizontally", "Output formatted to 4 decimals"],
	},
	"mars-rover-gridworld-bellman-update": {
		solverMethod: "Bellman Expectation Equation Policy Evaluation Step",
		regularization: "Discount factor gamma read from input line 1",
		formula: "V(s) = sum_a pi(a|s) * [ R(s, a) + gamma * sum_{s'} P(s' | s, a) * V(s') ]",
		conventions: "Equiprobable or given policy probabilities",
		outputPrecision: "Updated state values space-separated, 4 decimal places",
		extraConstraints: ["Bellman expectation equation", "Discount factor gamma from input"],
	},
	"lunar-lander-q-learning-update": {
		solverMethod: "Temporal Difference Q-Learning (Off-Policy TD Control) Step",
		learningRate: "alpha read from input line 1",
		regularization: "Discount factor gamma read from input line 1",
		formula: "TD_target = reward + gamma * max_{a'} Q(s', a'); Q(s, a) := Q(s, a) + alpha * (TD_target - Q(s, a))",
		conventions: "If next state s' is terminal, TD_target is reward alone",
		outputPrecision: "Updated Q(s, a) value formatted to 4 decimal places",
		extraConstraints: ["TD error: r + gamma*max_a' Q(s', a') - Q(s, a)", "Q := Q + alpha * TD_error"],
	},
	"multi-armed-bandit-epsilon-greedy": {
		solverMethod: "Multi-Armed Bandit Epsilon-Greedy Action Selection & Value Update",
		learningRate: "Sample-average update: Q(a) := Q(a) + (1 / N(a)) * (reward - Q(a))",
		tolerance: "epsilon read from input line 1",
		conventions: "Break ties in argmax Q(a) by selecting lower arm index",
		outputPrecision: "K updated arm values space-separated, 4 decimal places",
		extraConstraints: ["Sample-average update: Q := Q + (1/N)*(r - Q)", "Break ties by lower arm index"],
	},
	"casino-upper-confidence-bound-ucb1": {
		solverMethod: "Upper Confidence Bound (UCB1) Multi-Armed Bandit Action Selection",
		formula: "UCB_i = Q_i + c * sqrt((2 * ln(total_steps)) / n_i)",
		conventions: "Exploration constant c read from input line 1. Natural log ln. Break ties by lower arm index",
		outputPrecision: "Line 1: UCB scores for all arms (4 decimals), Line 2: selected arm index (integer)",
		extraConstraints: ["UCB = Q + c * sqrt(2*ln(N) / n_i)", "Break ties by lower index"],
	},
	"subway-agent-policy-evaluation-iterative": {
		solverMethod: "Iterative Policy Evaluation over Finite Markov Decision Process",
		regularization: "Discount factor gamma read from input line 1",
		tolerance: "eps = 1e-4 stopping condition",
		iterations: "max_sweeps = 100",
		formula: "V_{k+1}(s) = sum_a pi(a|s) * [ R(s, a) + gamma * sum_{s'} P(s'|s, a) * V_k(s') ]",
		conventions: "Synchronous updates: all state values updated using previous sweep values",
		outputPrecision: "State values space-separated, 4 decimal places",
		extraConstraints: ["Synchronous sweeps", "Stop when max|V_{k+1} - V_k| < 1e-4 or 100 sweeps"],
	},
	"robot-arm-discounted-cumulative-return": {
		solverMethod: "Discounted Cumulative Return (G_t) Trajectory Calculation",
		regularization: "Discount factor gamma read from input line 1 (0 <= gamma <= 1)",
		formula: "G_t = sum_{k=0}^{T - t - 1} gamma^k * R_{t + k + 1}",
		conventions: "Computes return for each timestep from t = 0 to T-1 using backward recursion: G_t = R_{t+1} + gamma * G_{t+1}",
		outputPrecision: "T return values space-separated, 4 decimal places",
		extraConstraints: ["Backward recursion: G_t = R_{t+1} + gamma * G_{t+1}", "Discount factor gamma from input"],
	},
};
