import { ProblemHyperparameterSpec } from "../hyperparameter-renderer";

export const storyProblemSpecs: Record<string, ProblemHyperparameterSpec> = {
	"the-guilds-treasury": {
		solverMethod: "Hash Map / Two-Sum Target Search",
		conventions: "Find two distinct indices i < j such that arr[i] + arr[j] == target. 0-indexed positions. If multiple pairs exist, return the one with smallest i",
		outputPrecision: "Two space-separated 0-indexed integers: i j",
		extraConstraints: ["0-indexed positions: i < j", "Return smallest first index if multiple solutions exist"],
	},
	"harvest-of-eldoria": {
		solverMethod: "Kadane's Algorithm (Maximum Subarray Sum)",
		formula: "max_so_far = max(num, max_so_far + num)",
		conventions: "Subarray must be contiguous and non-empty. Array can contain negative numbers",
		outputPrecision: "Single integer: maximum contiguous sum",
		extraConstraints: ["Contiguous non-empty subarray", "Linear time O(N) Kadane's algorithm"],
	},
	"shield-wall-formations": {
		solverMethod: "Two Pointers (Container With Most Water)",
		formula: "Area = min(height[left], height[right]) * (right - left)",
		conventions: "Move the pointer with the smaller height inward at each step",
		outputPrecision: "Single integer: maximum trapped area",
		extraConstraints: ["Two pointers moving inward", "O(N) time complexity"],
	},
	"the-wandering-alchemists-stash": {
		solverMethod: "Prefix Sum / Zero-Sum Subarray Detection",
		conventions: "Use hash set/map of prefix sums to find longest contiguous subarray with sum 0",
		outputPrecision: "Single integer: maximum length of zero-sum subarray",
		extraConstraints: ["Prefix sum hash table", "Return 0 if no zero-sum subarray exists"],
	},
	"beacon-towers-of-gondor": {
		solverMethod: "Monotonic Decreasing Stack (Next Greater Element)",
		conventions: "Find distance to next greater element to the right. 0-indexed. If none exists, output 0",
		outputPrecision: "N space-separated integers",
		extraConstraints: ["Next greater element distance", "Output 0 if no greater tower to the right"],
	},
	"the-lost-expedition-supplies": {
		solverMethod: "Sliding Window / Minimum Size Subarray Sum",
		conventions: "Find minimum length of contiguous subarray with sum >= target. If none exists, return 0",
		outputPrecision: "Single integer: minimum length or 0",
		extraConstraints: ["Contiguous subarray sum >= target", "Return 0 if impossible"],
	},
	"caravan-merchandise-majority": {
		solverMethod: "Boyer-Moore Majority Voting Algorithm",
		formula: "if count == 0: candidate = x; count += (x == candidate ? 1 : -1)",
		conventions: "Majority element appears strictly more than floor(N / 2) times",
		outputPrecision: "Single integer: the majority element",
		extraConstraints: ["O(N) time, O(1) space Boyer-Moore", "Guaranteed to exist"],
	},
	"the-emperors-spiral-tomb": {
		solverMethod: "Clockwise Spiral Matrix Traversal",
		conventions: "Traverse matrix in order: right, down, left, up while shrinking boundaries",
		outputPrecision: "All N*M elements space-separated in spiral order",
		extraConstraints: ["4 boundary pointers: top, bottom, left, right", "Clockwise order"],
	},
	"fortress-wall-water-trapping": {
		solverMethod: "Trapping Rain Water (Two Pointers / Prefix-Suffix Max)",
		formula: "water_i = max(0, min(left_max[i], right_max[i]) - height[i])",
		conventions: "Compute total units of trapped rain water across all bars",
		outputPrecision: "Single integer: total trapped water",
		extraConstraints: ["min(left_max, right_max) - height", "O(N) time complexity"],
	},
	"the-kings-tournament-eliminations": {
		solverMethod: "Josephus Problem / Modular Arithmetic Elimination",
		formula: "J(n, k) = (J(n - 1, k) + k) % n with base case J(1, k) = 0",
		conventions: "1-indexed survivor rank: J(n, k) + 1",
		outputPrecision: "Single integer: 1-indexed survivor position",
		extraConstraints: ["Josephus recurrence", "Output 1-indexed position"],
	},
	"the-ancient-cipher-of-karnak": {
		solverMethod: "Valid Anagram / Frequency Count Array",
		conventions: "Compare character counts of two strings across lowercase English letters a-z",
		outputPrecision: "Boolean string: true or false",
		extraConstraints: ["Case-sensitive English characters", "O(N) frequency matching"],
	},
	"scroll-of-the-whispering-monks": {
		solverMethod: "Longest Palindromic Substring (Expand Around Center)",
		conventions: "Expand around all 2N - 1 possible centers (single characters and pairs). Return longest substring. Tie-break: earliest starting index",
		outputPrecision: "String: the longest palindromic substring",
		extraConstraints: ["Continuous palindrome", "Earliest substring on tie"],
	},
	"the-scribes-longest-unique-substring": {
		solverMethod: "Sliding Window with Last Seen Character Index",
		conventions: "Longest substring without repeating characters",
		outputPrecision: "Single integer: length of longest unique substring",
		extraConstraints: ["Sliding window with character index hash map", "O(N) time"],
	},
	"runes-of-alchemical-transmutation": {
		solverMethod: "String Edit Distance / Levenshtein Dynamic Programming",
		formula: "dp[i][j] = min(dp[i-1][j]+1, dp[i][j-1]+1, dp[i-1][j-1] + (s1[i]!=s2[j]))",
		conventions: "Allowed operations: insert, delete, replace (each cost 1)",
		outputPrecision: "Single integer: minimum edit distance",
		extraConstraints: ["Standard Levenshtein cost 1", "O(N*M) DP grid"],
	},
	"the-archmages-common-incantation": {
		solverMethod: "Longest Common Prefix (LCP) Horizontal Scanning",
		conventions: "Compare characters at index i across all strings until mismatch or end of shortest string",
		outputPrecision: "String: common prefix or empty string if none",
		extraConstraints: ["Prefix must be common to all strings", "Empty string if no common prefix"],
	},
	"message-in-the-stellar-bottle": {
		solverMethod: "Reverse Words in String (In-Place / Two Pointers)",
		conventions: "Reverse the sequence of words. Reduce multiple spaces to single space and trim leading/trailing whitespace",
		outputPrecision: "Single string of cleaned space-separated reversed words",
		extraConstraints: ["Clean multiple spaces to single space", "No leading or trailing spaces"],
	},
	"the-kings-roman-numeral-decree": {
		solverMethod: "Roman Numeral to Integer Conversion",
		conventions: "Standard subtractive notation: IV=4, IX=9, XL=40, XC=90, CD=400, CM=900. If current value < next value, subtract current value",
		outputPrecision: "Single integer in range 1 to 3999",
		extraConstraints: ["Standard Roman numerals", "Subtractive notation rules"],
	},
	"astral-message-frequency-sort": {
		solverMethod: "Character Frequency Sorting (Bucket Sort / Max-Heap)",
		conventions: "Sort characters descending by frequency. Break frequency ties by ASCII order",
		outputPrecision: "String with characters repeated by frequency",
		extraConstraints: ["Sort descending by frequency", "Tie break by ASCII order"],
	},
	"the-goblins-word-pattern": {
		solverMethod: "Bijection / Two-Way Character to Word Mapping",
		conventions: "Each pattern character must map uniquely to one word and vice versa (1-to-1 bijection)",
		outputPrecision: "Boolean string: true or false",
		extraConstraints: ["Full bijection: pattern -> word and word -> pattern", "Case-sensitive exact match"],
	},
	"the-forbidden-palindromic-inscription": {
		solverMethod: "Valid Palindrome with Alphanumeric Filtering",
		conventions: "Ignore non-alphanumeric characters, convert all letters to lowercase, check palindrome via two pointers",
		outputPrecision: "Boolean string: true or false",
		extraConstraints: ["Case-insensitive", "Ignore spaces and punctuation"],
	},
	"the-pharaohs-prime-gold": {
		solverMethod: "Sieve of Eratosthenes Prime Counting",
		conventions: "Count all prime numbers strictly less than N",
		outputPrecision: "Single integer: count of primes < N",
		extraConstraints: ["Sieve of Eratosthenes O(N log log N)", "Strictly less than N"],
	},
	"the-clockwork-observatory": {
		solverMethod: "Greatest Common Divisor (Euclidean Algorithm) & LCM",
		formula: "gcd(a, b) = b == 0 ? a : gcd(b, a % b); lcm(a, b) = (a * b) / gcd(a, b)",
		conventions: "Handles large 64-bit integers",
		outputPrecision: "Two space-separated integers: GCD LCM",
		extraConstraints: ["Euclidean algorithm", "64-bit integer overflow protection"],
	},
	"mystic-powers-of-the-oracle": {
		solverMethod: "Fast Exponentiation (Binary Exponentiation by Squaring)",
		formula: "x^n = (n % 2 == 0) ? (x^2)^(n/2) : x * (x^2)^((n-1)/2)",
		conventions: "Handle negative powers: x^(-n) = 1 / (x^n)",
		outputPrecision: "Single real number formatted to 4 decimal places",
		extraConstraints: ["O(log N) binary exponentiation", "Handle negative exponent n < 0"],
	},
	"the-alchemists-fibonacci-elixir": {
		solverMethod: "Fibonacci Sequence with Modulo 10^9 + 7",
		formula: "F(0) = 0, F(1) = 1, F(n) = (F(n-1) + F(n-2)) % (10^9 + 7)",
		conventions: "Use iterative or matrix exponentiation modulo 1000000007",
		outputPrecision: "Single integer modulo 10^9 + 7",
		extraConstraints: ["Modulo 1000000007", "O(N) or O(log N) complexity"],
	},
	"the-treasurers-coin-cycles": {
		solverMethod: "Happy Number Cycle Detection (Floyd's Tortoise and Hare)",
		formula: "Sum of squares of digits",
		conventions: "Fast and slow pointers on digit square sum function to detect cycle vs reach 1",
		outputPrecision: "Boolean string: true or false",
		extraConstraints: ["Floyd's cycle detection", "Returns true if reaches 1, false on cycle"],
	},
	"the-kings-palindrome-number": {
		solverMethod: "Palindrome Integer Check Without String Conversion",
		conventions: "Negative numbers are not palindromes. Reverse half of the integer using modulo and division",
		outputPrecision: "Boolean string: true or false",
		extraConstraints: ["O(log10 N) time, O(1) extra space", "Negative numbers return false"],
	},
	"the-factor-tree-of-yggdrasil": {
		solverMethod: "Prime Factorization with Multiplicities",
		conventions: "Find all prime factors p with powers k such that N = prod(p^k). Output sorted by prime p",
		outputPrecision: "Lines of space-separated pairs: prime power",
		extraConstraints: ["Trial division up to sqrt(N)", "Sort factors ascending by prime base"],
	},
	"trailing-zeros-in-the-sacred-factorial": {
		solverMethod: "Legendre's Formula for Factorial Prime Factors",
		formula: "zeros = sum_{k=1}^infty floor(N / 5^k)",
		conventions: "Counts factors of 5 in N! without computing the full factorial",
		outputPrecision: "Single integer: count of trailing zeros in N!",
		extraConstraints: ["Legendre's formula: floor(N/5) + floor(N/25) + ...", "O(log5 N) time"],
	},
	"the-mathematicians-super-power": {
		solverMethod: "Modular Power of Large Array of Digits",
		formula: "a^b % 1337 where b is given as an array of digits",
		conventions: "Apply Euler's totient theorem or iterative Horner's rule",
		outputPrecision: "Single integer modulo 1337",
		extraConstraints: ["Modulo 1337", "Process array of digits b"],
	},
	"catalan-paths-to-the-celestial-citadel": {
		solverMethod: "Catalan Number C_n with Modulo 10^9 + 7",
		formula: "C_n = (2n)! / ((n+1)! * n!) = (1 / (n + 1)) * binom(2n, n)",
		conventions: "Modular inverse via Fermat's Little Theorem",
		outputPrecision: "Single integer modulo 10^9 + 7",
		extraConstraints: ["Modulo 1000000007", "Modular inverse for division"],
	},
	"caravans-across-the-great-dune": {
		solverMethod: "Two Pointers Array Partition / Dutch National Flag",
		conventions: "Partition array in-place into three sections relative to pivot",
		outputPrecision: "N space-separated integers",
		extraConstraints: ["O(N) single-pass in-place partition", "O(1) auxiliary space"],
	},
	"the-silk-road-checkpoints": {
		solverMethod: "Array Intersection of Sorted Lists (Two Pointers)",
		conventions: "Find common elements appearing in both sorted arrays. Maintain duplicates",
		outputPrecision: "Space-separated integers sorted ascending",
		extraConstraints: ["Two pointers on sorted arrays", "Retain multiplicity of intersection"],
	},
	"three-knights-honor-quest": {
		solverMethod: "3Sum Problem (Sorting + Two Pointers)",
		conventions: "Find all unique triplets [a, b, c] such that a + b + c == 0. Skip duplicate elements",
		outputPrecision: "Triplets space-separated, sorted lexicographically",
		extraConstraints: ["Sort array, then two pointers", "No duplicate triplets in output"],
	},
	"night-watch-perimeter-patrol": {
		solverMethod: "Interval Overlap Detection & Merging",
		conventions: "Sort intervals by start time. Merge overlapping intervals [start, end]",
		outputPrecision: "Merged intervals: start end",
		extraConstraints: ["Sort by start time", "Merge condition: next.start <= current.end"],
	},
	"the-alchemists-substance-blend": {
		solverMethod: "Subarray Sum Equals K (Prefix Sum Hash Map)",
		conventions: "Count number of continuous subarrays whose sum equals K. Hash map stores frequency of prefix sums",
		outputPrecision: "Single integer: count of matching subarrays",
		extraConstraints: ["Prefix sum hash table", "O(N) time complexity"],
	},
	"sort-colors-of-the-empire": {
		solverMethod: "Dutch National Flag 3-Way In-Place Sort",
		conventions: "Sort array containing 0s, 1s, and 2s in-place in a single pass with low, mid, high pointers",
		outputPrecision: "Sorted integers space-separated",
		extraConstraints: ["Single pass O(N), O(1) space", "No library sort allowed"],
	},
	"merging-the-royal-archives": {
		solverMethod: "Merge Two Sorted Arrays in O(N + M)",
		conventions: "Merge two sorted arrays into a single combined sorted array using two pointers",
		outputPrecision: "Merged space-separated integers sorted ascending",
		extraConstraints: ["O(N + M) two-pointer merge", "Stable sorted order"],
	},
	"traversing-the-mountain-interval": {
		solverMethod: "Insert Interval into Non-Overlapping Sorted Intervals",
		conventions: "Insert new interval [start, end] and merge all overlapping intervals",
		outputPrecision: "Merged non-overlapping intervals",
		extraConstraints: ["Preserve sorted order by start time", "Linear scan merge"],
	},
	"searching-the-royal-archives": {
		solverMethod: "Classical Binary Search in Sorted Array",
		conventions: "0-indexed. Return index of target if found, else -1",
		outputPrecision: "Single integer: index or -1",
		extraConstraints: ["O(log N) binary search", "Return -1 if target not present"],
	},
	"the-deepest-mine-shaft": {
		solverMethod: "Search in Rotated Sorted Array",
		conventions: "Binary search on shifted sorted array. Determine which half is monotonically ordered",
		outputPrecision: "Single integer: index or -1",
		extraConstraints: ["O(log N) time", "Return -1 if element absent"],
	},
	"calibrating-the-siege-catapult": {
		solverMethod: "Find First and Last Position of Element in Sorted Array",
		conventions: "Two binary searches for lower bound and upper bound. 0-indexed. If not found, return -1 -1",
		outputPrecision: "Two space-separated integers: first_pos last_pos",
		extraConstraints: ["O(log N) time", "Return -1 -1 if target absent"],
	},
	"the-archers-peak-elevation": {
		solverMethod: "Find Peak Element in Unsorted Array",
		conventions: "A peak element is strictly greater than its neighbors. Binary search slope direction",
		outputPrecision: "Single integer: index of any peak element",
		extraConstraints: ["O(log N) time", "Return 0-indexed peak position"],
	},
	"dragon-smaugs-feast": {
		solverMethod: "Koko Eating Bananas (Binary Search on Answer)",
		conventions: "Find minimum integer eating speed K such that total hours spent <= H",
		outputPrecision: "Single integer: minimum eating speed K",
		extraConstraints: ["Binary search in range [1, max(piles)]", "Ceiling division for hours"],
	},
	"capacity-of-the-desert-caravan": {
		solverMethod: "Capacity To Ship Packages Within D Days (Binary Search on Answer)",
		conventions: "Find minimum conveyor capacity to deliver all weights in order within D days",
		outputPrecision: "Single integer: minimum daily capacity",
		extraConstraints: ["Search range [max(weights), sum(weights)]", "Greedy validation per candidate capacity"],
	},
	"the-royal-lumberjacks-harvest": {
		solverMethod: "Woodcutting Sawblade Height (Binary Search on Answer)",
		conventions: "Find maximum integer blade height H that yields at least M meters of wood: sum(max(0, tree_i - H)) >= M",
		outputPrecision: "Single integer: maximum height H",
		extraConstraints: ["Binary search blade height", "Sum of upper wood cuts >= M"],
	},
	"aggressive-horses-of-the-steppes": {
		solverMethod: "Aggressive Cows / Stalls Placement (Binary Search on Distance)",
		conventions: "Maximize minimum distance between any two assigned stalls. Greedy placement validation",
		outputPrecision: "Single integer: largest minimum distance",
		extraConstraints: ["Sort stall coordinates", "Binary search distance range [1, max - min]"],
	},
	"the-dragons-hoard-redistribution": {
		solverMethod: "Greedy Coin Change / Largest Denomination First",
		conventions: "Canonical coin denominations. Greedily pick largest possible denomination",
		outputPrecision: "Single integer: minimum total coins needed",
		extraConstraints: ["Greedy pick largest denomination", "Exact change required"],
	},
	"fueling-the-starship-odyssey": {
		solverMethod: "Gas Station Circular Tour (Greedy Single Pass)",
		conventions: "Find unique 0-indexed starting station index that allows completing full circle. If impossible, return -1",
		outputPrecision: "Single integer: starting station index or -1",
		extraConstraints: ["O(N) time single pass", "Return -1 if sum(gas) < sum(cost)"],
	},
	"the-royal-couriers-schedule": {
		solverMethod: "Non-Overlapping Intervals (Greedy Interval Scheduling)",
		conventions: "Sort intervals by end time. Greedily pick intervals that end earliest to minimize removals",
		outputPrecision: "Single integer: minimum number of intervals to remove",
		extraConstraints: ["Sort by end time", "Greedy interval scheduling"],
	},
	"the-alchemists-potion-bottles": {
		solverMethod: "Assign Cookies / Two Pointers Greedy Matching",
		conventions: "Sort greed factors and available sizes ascending. Match smallest satisfactory bottle",
		outputPrecision: "Single integer: maximum satisfied patrons",
		extraConstraints: ["Sort both arrays", "Greedy matching via two pointers"],
	},
	"jumping-through-the-floating-islands": {
		solverMethod: "Jump Game II (Greedy Farthest Reach / BFS Layers)",
		conventions: "Find minimum number of jumps to reach index N - 1 from index 0",
		outputPrecision: "Single integer: minimum jump count",
		extraConstraints: ["O(N) greedy window tracking farthest reach", "Guaranteed reachable"],
	},
	"the-minimalist-coin-master": {
		solverMethod: "Coin Change Problem (Unbounded Knapsack Dynamic Programming)",
		formula: "dp[a] = min(dp[a], dp[a - coin] + 1)",
		conventions: "If amount cannot be made up by any combination, return -1",
		outputPrecision: "Single integer: minimum coins or -1",
		extraConstraints: ["dp[0] = 0, dp[others] = infinity", "Return -1 if impossible"],
	},
	"reorganizing-the-ancient-scroll": {
		solverMethod: "Reorganize String (Max-Heap / Greedy Most Frequent First)",
		conventions: "Rearrange characters so no two adjacent characters are identical. If impossible, return empty string",
		outputPrecision: "Reorganized string or empty string",
		extraConstraints: ["Max-heap of character frequencies", "Return empty string if impossible"],
	},
	"task-scheduling-for-the-royal-smithy": {
		solverMethod: "Task Scheduler with Cooldown Period (Greedy Max Frequency Math)",
		formula: "min_intervals = max((max_freq - 1) * (n + 1) + count_max_freq, total_tasks)",
		conventions: "Cooldown n periods between identical tasks",
		outputPrecision: "Single integer: least number of units of time",
		extraConstraints: ["Cooldown interval n", "Math / priority queue scheduling"],
	},
	"candy-distribution-at-the-orphanage": {
		solverMethod: "Candy Distribution (Two-Pass Greedy: Left and Right)",
		conventions: "Every child gets at least 1 candy. Higher rated neighbor gets more candies. Pass left-to-right, then right-to-left taking max",
		outputPrecision: "Single integer: minimum total candies",
		extraConstraints: ["Two-pass greedy algorithm", "All children get >= 1 candy"],
	},
	"the-partition-labels-of-the-library": {
		solverMethod: "Partition Labels (Greedy Last Occurrence Tracking)",
		conventions: "Partition string into as many parts as possible such that each letter appears in at most one part",
		outputPrecision: "Space-separated integers: lengths of each partition",
		extraConstraints: ["Track last occurrence index of each character", "Expand window until reaching max last occurrence"],
	},
	"citadel-defense-towers": {
		solverMethod: "Monotonic Stack (Daily Temperatures Pattern)",
		conventions: "Find number of days until warmer temperature. 0-indexed. If none exists, output 0",
		outputPrecision: "N space-separated integers",
		extraConstraints: ["Monotonic decreasing stack", "Output 0 if no warmer day ahead"],
	},
	"bracket-glyphs-of-the-mage": {
		solverMethod: "Valid Parentheses (Stack Character Matching)",
		conventions: "Matching bracket pairs: (), {}, []. Brackets must close in correct order",
		outputPrecision: "Boolean string: true or false",
		extraConstraints: ["LIFO stack validation", "Empty string is valid"],
	},
	"the-mountain-ridge-silhouettes": {
		solverMethod: "Largest Rectangle in Histogram (Monotonic Increasing Stack)",
		conventions: "Compute maximum area of rectangle within bar heights. Pop stack when incoming bar is shorter",
		outputPrecision: "Single integer: maximum rectangular area",
		extraConstraints: ["O(N) monotonic stack", "Sentinel 0 height at end"],
	},
	"the-archmages-reverse-polish-scroll": {
		solverMethod: "Evaluate Reverse Polish Notation (Stack Evaluation)",
		conventions: "Supported operators: +, -, *, /. Division truncates toward zero",
		outputPrecision: "Single integer: evaluated expression result",
		extraConstraints: ["Truncate division toward zero: int(a / b)", "Pop operands in correct order"],
	},
	"collapsing-cavern-stalactites": {
		solverMethod: "Asteroid Collision (Stack Simulation)",
		conventions: "Positive moves right, negative moves left. Collision occurs when positive is followed by negative. Equal size asteroids annihilate each other",
		outputPrecision: "Surviving asteroid integers space-separated",
		extraConstraints: ["Simulate via stack", "Empty output if all collide"],
	},
	"the-grand-bazaars-stock-spans": {
		solverMethod: "Online Stock Span (Monotonic Stack Consecutive Days)",
		conventions: "Span is maximum consecutive days (including today) where price <= today's price",
		outputPrecision: "N space-separated integer spans",
		extraConstraints: ["Monotonic stack of (price, span)", "Consecutive days up to today"],
	},
	"simplifying-the-ancient-directory": {
		solverMethod: "Simplify Canonical Unix File Path (Stack Tokenization)",
		conventions: "Split by '/', push valid directory names, pop on '..', ignore '.' and empty tokens. Output begins with '/' and has no trailing slash",
		outputPrecision: "Canonical simplified path string",
		extraConstraints: ["Root path '/' if stack empty", "No trailing slash for non-root paths"],
	},
	"the-colosseum-arena-floor": {
		solverMethod: "Trapping Rain Water via Monotonic Decreasing Stack",
		conventions: "Track bar indices in monotonic stack. When current bar is taller than top, pop bounded trough and accumulate trapped water",
		outputPrecision: "Single integer: total trapped water units",
		extraConstraints: ["Bounded height: min(height[curr], height[stack_top]) - height[trough]", "O(N) time"],
	},
	"minotaurs-labyrinth-escape": {
		solverMethod: "Breadth-First Search (BFS) Shortest Path in Grid",
		conventions: "Move 4-directionally (up, down, left, right). Obstacles marked '1', open cells '0'. Return shortest distance from top-left to bottom-right, or -1 if unreachable",
		outputPrecision: "Single integer: shortest path step count or -1",
		extraConstraints: ["4-directional BFS queue", "Return -1 if destination unreachable"],
	},
	"rotting-oranges-in-the-granary": {
		solverMethod: "Multi-Source BFS (Rotting Oranges)",
		conventions: "All initially rotten oranges start at minute 0. 4-directional spread. Return minimum minutes until all fresh oranges rot, or -1 if any fresh remains",
		outputPrecision: "Single integer: minutes or -1",
		extraConstraints: ["Multi-source queue initialization", "Return -1 if fresh oranges remain isolated"],
	},
	"word-ladder-of-the-hierophant": {
		solverMethod: "Word Ladder (Bidirectional / Standard BFS)",
		conventions: "Change 1 letter at a time to form valid words from word list. Return shortest sequence length from beginWord to endWord, or 0 if impossible",
		outputPrecision: "Single integer: transformation sequence length or 0",
		extraConstraints: ["Words differ by exactly 1 character", "Return 0 if endWord unreachable"],
	},
	"shortest-path-in-binary-matrix": {
		solverMethod: "8-Directional BFS in Binary Grid",
		conventions: "Cells with 0 are clear, 1 are blocked. Move in 8 cardinal and diagonal directions. Path length is number of visited cells. Return -1 if blocked",
		outputPrecision: "Single integer: path length or -1",
		extraConstraints: ["8-directional adjacency", "Start and end must be 0"],
	},
	"open-the-royal-vault-lock": {
		solverMethod: "Open the Lock (BFS on 4-Digit Combination Graph)",
		conventions: "Wheels turn forward or backward modulo 10 (0 <-> 9). Avoid deadends. Start at '0000'. Return minimum turns to target, or -1 if trapped",
		outputPrecision: "Single integer: minimum turns or -1",
		extraConstraints: ["Circular digits (0 to 9)", "Return -1 if start in deadends or unreachable"],
	},
	"the-knights-errant-journey": {
		solverMethod: "Minimum Knight Moves on Infinite Chessboard (Symmetric BFS)",
		conventions: "Knight moves in 8 L-shaped patterns: (+-1, +-2) and (+-2, +-1). Exploit 4-quadrant symmetry: target (|x|, |y|). Return minimum moves",
		outputPrecision: "Single integer: minimum knight moves",
		extraConstraints: ["8 knight move offsets", "Symmetric absolute coordinates (|x|, |y|)"],
	},
	"citadel-gates-and-dungeons": {
		solverMethod: "Walls and Gates (Multi-Source BFS from Gates)",
		conventions: "Empty rooms initialized to INF (2147483647). Gates are 0, walls are -1. Fill empty rooms with shortest distance to nearest gate",
		outputPrecision: "Grid of integers with updated distances",
		extraConstraints: ["Multi-source BFS initialized with all gates", "Do not overwrite walls (-1)"],
	},
	"sacred-flood-fill": {
		solverMethod: "Flood Fill Algorithm (BFS / DFS)",
		conventions: "Change color of starting pixel (sr, sc) and all 4-directionally connected pixels of the same initial color to new color",
		outputPrecision: "Modified 2D integer grid",
		extraConstraints: ["4-directional connectivity", "No-op if new color == old color"],
	},
	"academy-course-prerequisites": {
		solverMethod: "Course Schedule / Topological Sort (Kahn's Algorithm via In-Degree)",
		conventions: "Detect directed cycles in prerequisite graph. If in-degree queue exhausts all courses, return true (feasible), else false",
		outputPrecision: "Boolean string: true or false",
		extraConstraints: ["Kahn's algorithm using in-degree array", "Cycle detection in directed graph"],
	},
	"islands-of-the-archipelago": {
		solverMethod: "Number of Connected Components / Islands (DFS / BFS Traversal)",
		conventions: "Land marked '1', water '0'. Island formed by 4-directionally adjacent land cells. Count total disconnected islands",
		outputPrecision: "Single integer: island count",
		extraConstraints: ["4-directional connectivity", "Sink visited land cells to '0'"],
	},
	"kingdom-alliance-factions": {
		solverMethod: "Number of Connected Components in Undirected Graph (Disjoint Set Union / DSU)",
		conventions: "Nodes 0 to N-1. Union-Find with path compression. Count number of distinct connected components",
		outputPrecision: "Single integer: component count",
		extraConstraints: ["Disjoint Set Union (DSU)", "Count unique root representatives"],
	},
	"network-delay-in-the-empire": {
		solverMethod: "Dijkstra's Shortest Path Algorithm (Single Source Shortest Path)",
		conventions: "Directed edges with positive transmission times. Return time for all nodes to receive signal from source K. If impossible, return -1",
		outputPrecision: "Single integer: maximum shortest path or -1",
		extraConstraints: ["Min-heap priority queue Dijkstra", "Return -1 if any node unreachable"],
	},
	"royal-astronomers-star-clusters": {
		solverMethod: "Graph Bipartiteness Check (Two-Coloring via BFS / DFS)",
		conventions: "Graph is bipartite if vertices can be partitioned into two independent sets with no intra-set edges. Check for odd-length cycles",
		outputPrecision: "Boolean string: true or false",
		extraConstraints: ["Two-coloring algorithm", "Return false if odd cycle found"],
	},
	"cycle-in-the-ancient-teleport-network": {
		solverMethod: "Directed Graph Cycle Detection (3-Color DFS: White, Gray, Black)",
		conventions: "State 0: unvisited, State 1: visiting (in current recursion stack), State 2: fully processed. Cycle detected if edge points to node in State 1",
		outputPrecision: "Boolean string: true or false",
		extraConstraints: ["3-color DFS cycle detection", "True if cycle exists, else false"],
	},
	"continental-divide-water-flow": {
		solverMethod: "Pacific Atlantic Water Flow (Reverse BFS/DFS from Boundaries)",
		conventions: "Water flows to equal or lower height. Start search from Pacific boundary and Atlantic boundary going uphill. Find cells reaching both oceans",
		outputPrecision: "Sorted coordinates [r, c] reaching both oceans",
		extraConstraints: ["Reverse flow search from oceans", "Height condition: neighbor.height >= current.height"],
	},
	"alien-scroll-alphabet-order": {
		solverMethod: "Alien Dictionary (Topological Sort on Character Dependency Graph)",
		conventions: "Extract pairwise order from adjacent dictionary words. Detect prefix anomaly (e.g. 'abc' before 'ab' is invalid). Topological sort via Kahn's algorithm",
		outputPrecision: "String of unique characters in topological order or empty string if invalid",
		extraConstraints: ["Prefix anomaly returns empty string", "Cycle returns empty string"],
	},
	"the-archmages-climbing-steps": {
		solverMethod: "Climbing Stairs (Fibonacci Dynamic Programming)",
		formula: "dp[i] = dp[i-1] + dp[i-2] with dp[1] = 1, dp[2] = 2",
		conventions: "Allowed step sizes: 1 or 2 steps",
		outputPrecision: "Single integer: distinct ways to climb N steps",
		extraConstraints: ["O(N) time, O(1) space", "Base cases: dp[1]=1, dp[2]=2"],
	},
	"the-dragon-vault-coin-combinations": {
		solverMethod: "Coin Change II (Total Distinct Combinations / Unbounded Knapsack)",
		formula: "dp[a] += dp[a - coin]",
		conventions: "Loop over coins outer, amounts inner to ensure unique combinations without permutation counting",
		outputPrecision: "Single integer: total distinct combinations",
		extraConstraints: ["Outer loop: coins; Inner loop: amounts", "dp[0] = 1"],
	},
	"the-vault-of-the-dwarven-king": {
		solverMethod: "0/1 Knapsack Problem (Dynamic Programming)",
		formula: "dp[w] = max(dp[w], dp[w - weight[i]] + value[i])",
		conventions: "Items can each be taken at most once. Iterate backwards on knapsack capacity",
		outputPrecision: "Single integer: maximum achievable value",
		extraConstraints: ["Iterate capacity backwards to ensure 0/1 constraint", "O(N * W) time"],
	},
	"the-longest-ascension-of-stars": {
		solverMethod: "Longest Increasing Subsequence (LIS via Patience Sorting / Binary Search)",
		formula: "Tails array with binary search (bisect_left)",
		conventions: "Strictly increasing subsequence",
		outputPrecision: "Single integer: length of LIS",
		extraConstraints: ["O(N log N) patience sorting", "Strictly increasing (elements must be >)"],
	},
	"the-scribes-edit-scrolls": {
		solverMethod: "Longest Common Subsequence (LCS Dynamic Programming)",
		formula: "if s1[i]==s2[j]: dp[i][j] = 1 + dp[i-1][j-1]; else: max(dp[i-1][j], dp[i][j-1])",
		conventions: "Subsequence characters do not need to be contiguous",
		outputPrecision: "Single integer: length of longest common subsequence",
		extraConstraints: ["Standard 2D DP grid", "O(N * M) time complexity"],
	},
	"the-wandering-monks-paths": {
		solverMethod: "Unique Paths in Grid with Obstacles (Dynamic Programming)",
		formula: "if grid[r][c] == 1: dp[r][c] = 0; else: dp[r][c] = dp[r-1][c] + dp[r][c-1]",
		conventions: "Can only move down or right. Starting cell or ending cell with obstacle has 0 paths",
		outputPrecision: "Single integer: total unique paths",
		extraConstraints: ["Move only right or down", "Obstacles marked 1 yield 0 paths"],
	},
	"decoding-the-oracle-prophecy": {
		solverMethod: "Decode Ways (Dynamic Programming with Character Encoding Constraints)",
		conventions: "Single digit valid if '1' <= s[i] <= '9'. Two digits valid if '10' <= s[i-1..i] <= '26'. Leading '0' is invalid",
		outputPrecision: "Single integer: number of possible decodings",
		extraConstraints: ["Leading zeros return 0", "Valid 2-digit range: 10 to 26"],
	},
	"the-empress-maximal-square": {
		solverMethod: "Maximal Square of 1s in Binary Matrix (Dynamic Programming)",
		formula: "dp[i][j] = min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1]) + 1",
		conventions: "Find maximum area of square submatrix containing only 1s",
		outputPrecision: "Single integer: maximum area (side_length^2)",
		extraConstraints: ["Square of 1s: min of left, top, top-left + 1", "Output is area: max_side * max_side"],
	},
	"the-cunning-thief-of-baghdad": {
		solverMethod: "House Robber (Linear Dynamic Programming with Non-Adjacent Constraint)",
		formula: "dp[i] = max(dp[i-1], dp[i-2] + nums[i])",
		conventions: "Cannot rob two adjacent houses",
		outputPrecision: "Single integer: maximum stolen gold",
		extraConstraints: ["No two adjacent elements can be selected", "O(N) time, O(1) space"],
	},
	"the-ancient-lexicon-word-break": {
		solverMethod: "Word Break (Dynamic Programming with Dictionary Matching)",
		formula: "dp[i] = true if dp[j] == true and s[j..i] in dictionary for some j < i",
		conventions: "Base case dp[0] = true. Determine if entire string can be segmented",
		outputPrecision: "Boolean string: true or false",
		extraConstraints: ["Words can be reused multiple times", "dp[0] = true"],
	},
	"the-lone-sentinel-of-the-dune": {
		solverMethod: "Single Number via Bitwise XOR Cancellation",
		formula: "res = res ^ num",
		conventions: "Every element appears twice except for one unique element. a ^ a = 0, a ^ 0 = a",
		outputPrecision: "Single integer: the lone element",
		extraConstraints: ["O(N) time, O(1) space using XOR", "Exact cancellation"],
	},
	"counting-stars-in-the-binary-constellation": {
		solverMethod: "Number of 1 Bits (Hamming Weight / Brian Kernighan's Algorithm)",
		formula: "n = n & (n - 1) clears least significant set bit",
		conventions: "Count set bits of 32-bit unsigned integer",
		outputPrecision: "Single integer: count of 1 bits",
		extraConstraints: ["Brian Kernighan's bit trick", "32-bit unsigned integer"],
	},
	"arcane-addition-without-arithmetic": {
		solverMethod: "Sum of Two Integers Without Arithmetic Operators (+ or -)",
		formula: "sum = a ^ b, carry = (a & b) << 1; repeat until carry == 0",
		conventions: "Simulates digital half-adder / full-adder logic using bitwise operations",
		outputPrecision: "Single integer: a + b",
		extraConstraints: ["Do not use + or - operators", "Bitwise XOR and AND shift"],
	},
	"reversing-the-sacred-binary-mirror": {
		solverMethod: "Reverse Bits of 32-Bit Unsigned Integer",
		conventions: "Iterate 32 times: shift result left, add last bit of n, shift n right",
		outputPrecision: "Single unsigned 32-bit integer",
		extraConstraints: ["Exactly 32 bit reversals", "Unsigned 32-bit integer"],
	},
	"the-bitwise-conjunction-of-the-eclipse": {
		solverMethod: "Bitwise AND of Numbers Range [m, n]",
		formula: "Find common binary prefix of m and n by shifting right until m == n, then shift back",
		conventions: "Any bit that toggles within [m, n] becomes 0 in cumulative AND",
		outputPrecision: "Single integer: bitwise AND result",
		extraConstraints: ["O(log N) bit shifting to common prefix", "Do not loop over every number"],
	},
	"merging-the-royal-summons-intervals": {
		solverMethod: "Merge Intervals (Sorting by Start Time)",
		conventions: "Sort intervals by start coordinate ascending. Merge when current interval overlaps with previous",
		outputPrecision: "Merged interval pairs space-separated",
		extraConstraints: ["Sort intervals by start time", "Merge condition: next.start <= curr.end"],
	},
	"top-k-favored-relics": {
		solverMethod: "Top K Frequent Elements (Bucket Sort / Min-Heap)",
		conventions: "Count frequencies with hash map. Use frequency buckets to return K most frequent elements",
		outputPrecision: "K space-separated integers sorted descending by frequency",
		extraConstraints: ["O(N) time using bucket sort", "K most frequent elements"],
	},
	"sort-knights-by-chivalric-parity": {
		solverMethod: "Sort Array By Parity (In-Place Two Pointers)",
		conventions: "Move all even integers to front, followed by all odd integers. Relative order within parities can be arbitrary",
		outputPrecision: "Space-separated integers with evens preceding odds",
		extraConstraints: ["O(N) time, O(1) space two pointers", "All even integers before odd integers"],
	},
	"the-grand-architects-largest-number": {
		solverMethod: "Largest Number String Concatenation Comparator Sort",
		conventions: "Custom comparator for strings A and B: sort by (B + A) > (A + B). If highest element is '0', return '0'",
		outputPrecision: "String representing largest concatenated integer",
		extraConstraints: ["Sort strings by (b + a).compareTo(a + b)", "Handle all-zero array leading zeros: return '0'"],
	},
	"the-guild-hall-meeting-chambers": {
		solverMethod: "Meeting Rooms II (Minimum Conference Rooms / Two Pointers / Chronological Sweep)",
		conventions: "Separate start times and end times, sort both ascending. Increment room count on start, decrement on end. Track maximum concurrent rooms",
		outputPrecision: "Single integer: minimum meeting rooms required",
		extraConstraints: ["Chronological sweep-line / min-heap", "Strict end before start if end == start"],
	},
};
